apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: resource-manager
  title: "🗑️ Delete My Resources"
  description: |
    View and delete resources you have created via Backstage.
    Resources are automatically listed from your Terraform state.
  tags:
    - terraform
    - aws
    - delete
    - management
spec:
  owner: platform-team
  type: management

  parameters:
    - title: " Select Resource to Delete"
      description: |
        ## First: View Your Resources

        **Click here:** [View All Resources](/api/resources/resources)

        The API shows all resources. Find yours by your username in the `owner` field.
        Copy the `type` and `name` from your resource.

        Example response:
        ```json
        [
          {"type": "ec2", "owner": "your-username", "name": "ssm-role"},
          {"type": "s3", "owner": "your-username", "name": "my-bucket"}
        ]
        ```

        **Warning:** Deletion is permanent!
      required:
        - resourceType
        - resourceName
        - confirmDeletion
      properties:
        resourceType:
          title: " Resource Type"
          type: string
          enum:
            - s3
            - ec2
            - lambda
            - rds
          default: s3
          description: Type from API response (e.g., "s3", "ec2")
        resourceName:
          title: " Resource Name"
          type: string
          description: Name from API response (e.g., "my-bucket-name")
          ui:autofocus: true
          ui:placeholder: "my-bucket-name"
        confirmDeletion:
          title: " I CONFIRM I want to PERMANENTLY DELETE this resource"
          type: boolean
          default: false
          ui:widget: checkbox

  steps:
    - id: fetch-base
      name: Fetch Terraform Config
      if: ${{ parameters.confirmDeletion == true }}
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./terraform

    - id: terraform-destroy
      name: Destroy Resource
      if: ${{ parameters.confirmDeletion == true }}
      action: terraform:destroy
      input:
        terraformDir: ./terraform
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: ${{ parameters.resourceType }}/${{ user.entity.metadata.name | default('admin') }}/${{ parameters.resourceName }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        ownerEmail: ${{ user.entity.spec.profile.email | default('admin@darede.com.br') }}
        resourceOwner: ${{ user.entity.spec.profile.email | default('admin@darede.com.br') }}
        autoApprove: true

  output:
    links:
      - title: "🔙 Back to Templates"
        url: /create
      - title: "📂 S3 State Bucket"
        url: "https://console.aws.amazon.com/s3/buckets/poc-idp-tfstate"
    text:
      - title: Status
        content: |
          ${{ parameters.confirmDeletion == true ? '✅ Resource deleted successfully' : '❌ Deletion cancelled - confirmation required' }}
