apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: resource-manager
  title: "🗑️ Delete My Resources"
  description: |
    View and delete resources you have created via Backstage.
    Resources are automatically listed from your Terraform state.
  tags:
    - terraform
    - aws
    - delete
    - management
spec:
  owner: platform-team
  type: management

  parameters:
    - title: "📋 Select Resource to Delete"
      description: |
        ## Your Resources

        **[🔍 Click here to view your resources](https://backstage.timedevops.click/api/resources/resources?owner=${{ user.entity.metadata.name | default('admin') }})**

        The link above shows all resources you own in JSON format. Copy the resource details from there.

        Example response:
        ```json
        [
          {"type": "s3", "owner": "admin", "name": "my-bucket", ...}
        ]
        ```

        **Note:** Only resources you own can be deleted.
      required:
        - resourceType
        - resourceName
        - confirmDeletion
      properties:
        resourceType:
          title: "📦 Resource Type"
          type: string
          enum:
            - s3
            - ec2
            - lambda
            - rds
          default: s3
          description: Type of AWS resource to delete
        resourceName:
          title: "🏷️ Resource Name"
          type: string
          description: |
            Name of the resource (e.g., bucket name, instance ID).
            This is the "name" field from the API response.
          ui:autofocus: true
          ui:placeholder: "my-bucket-name"
        confirmDeletion:
          title: "⚠️ I CONFIRM I want to PERMANENTLY DELETE this resource"
          type: boolean
          default: false
          ui:widget: checkbox

  steps:
    - id: fetch-base
      name: Fetch Terraform Config
      if: ${{ parameters.confirmDeletion == true }}
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./terraform

    - id: terraform-destroy
      name: Destroy Resource
      if: ${{ parameters.confirmDeletion == true }}
      action: terraform:destroy
      input:
        terraformDir: ./terraform
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: ${{ parameters.resourceType }}/${{ user.entity.metadata.name | default('admin') }}/${{ parameters.resourceName }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        ownerEmail: ${{ user.entity.spec.profile.email | default('admin@darede.com.br') }}
        resourceOwner: ${{ user.entity.spec.profile.email | default('admin@darede.com.br') }}
        autoApprove: true

  output:
    links:
      - title: "🔙 Back to Templates"
        url: /create
      - title: "📂 S3 State Bucket"
        url: "https://console.aws.amazon.com/s3/buckets/poc-idp-tfstate"
    text:
      - title: Status
        content: |
          ${{ parameters.confirmDeletion == true ? '✅ Resource deleted successfully' : '❌ Deletion cancelled - confirmation required' }}
