apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: resource-manager
  title: "🗑️ Delete My Resources"
  description: |
    View and delete resources you have created via Backstage.
    Resources are automatically listed from your Terraform state.
  tags:
    - terraform
    - aws
    - delete
    - management
spec:
  owner: platform-team
  type: management

  parameters:
    - title: "📋 Select Resource to Delete"
      description: |
        ## Your Resources

        Resources are automatically loaded from your Terraform state bucket.
        Select a resource below to delete it.

        **Note:** Only resources you own are shown.
      required:
        - stateKey
        - confirmDeletion
      properties:
        stateKey:
          title: "📋 Terraform State Key"
          type: string
          description: |
            List your resources:
            curl https://backstage.timedevops.click/api/resources/resources?owner=${{ user.entity.metadata.name | default('admin') }}

            Copy the stateKey value (e.g., s3/admin/my-bucket)
          ui:autofocus: true
          ui:placeholder: "s3/admin/my-bucket-name"
        confirmDeletion:
          title: "⚠️ I CONFIRM I want to PERMANENTLY DELETE this resource"
          type: boolean
          default: false
          ui:widget: checkbox

    - title: "👤 Owner Verification"
      properties:
        owner:
          title: Owner (You)
          type: string
          default: ${{ user.entity.metadata.name | default('unknown') }}
          ui:readonly: true
        ownerEmail:
          title: Owner Email
          type: string
          default: ${{ user.entity.spec.profile.email | default('unknown@example.com') }}
          ui:readonly: true

  steps:
    - id: log-request
      name: Log Deletion Request
      action: debug:log
      input:
        message: |
          ⚠️ DELETION REQUEST
          State Key: ${{ parameters.stateKey }}/terraform.tfstate
          Owner: ${{ parameters.owner }} (${{ parameters.ownerEmail }})
          Confirmed: ${{ parameters.confirmDeletion }}

    - id: terraform-destroy
      name: Destroy Resource
      if: ${{ parameters.confirmDeletion == true }}
      action: terraform:destroy
      input:
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: ${{ parameters.stateKey }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        ownerEmail: ${{ parameters.ownerEmail }}
        resourceOwner: ${{ parameters.ownerEmail }}
        autoApprove: true

  output:
    links:
      - title: "🔙 Back to Templates"
        url: /create
      - title: "📂 S3 State Bucket"
        url: "https://console.aws.amazon.com/s3/buckets/poc-idp-tfstate"
    text:
      - title: Status
        content: |
          ${{ parameters.confirmDeletion == true ? '✅ Resource deleted successfully' : '❌ Deletion cancelled - confirmation required' }}
