apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: resource-manager
  title: "🗑️ Delete My Resources"
  description: |
    Delete resources you have created via Backstage.
    Paste the full Terraform state key to delete a resource.
  tags:
    - terraform
    - aws
    - delete
    - management
spec:
  owner: platform-team
  type: management

  parameters:
    - title: "🔍 Find Your Resource"
      description: |
        ## Step 1: List your resources

        Run this command in your terminal:
        ```bash
        aws s3 ls s3://poc-idp-tfstate/ --recursive --profile darede | grep terraform.tfstate
        ```

        ## Step 2: Copy the state key

        Find the resource you want to delete and copy the **full path** (without `terraform.tfstate`).

        **Examples:**
        | Type | State Key to Copy |
        |------|------------------|
        | S3 | `s3/admin/my-bucket` |
        | EC2 | `ec2/admin/my-instance` |
        | VPC | `vpc/admin/my-vpc` |
      required:
        - stateKey
        - confirmDeletion
      properties:
        stateKey:
          title: "📋 Terraform State Key"
          type: string
          description: "Full state key path (e.g., s3/admin/my-bucket)"
          ui:autofocus: true
          ui:placeholder: "s3/admin/my-bucket-name"
        confirmDeletion:
          title: "⚠️ I CONFIRM I want to PERMANENTLY DELETE this resource"
          type: boolean
          default: false
          ui:widget: checkbox

    - title: "👤 Owner Verification"
      properties:
        owner:
          title: Owner (You)
          type: string
          default: ${{ user.entity.metadata.name | default('unknown') }}
          ui:readonly: true
        ownerEmail:
          title: Owner Email
          type: string
          default: ${{ user.entity.spec.profile.email | default('unknown@example.com') }}
          ui:readonly: true

  steps:
    - id: log-request
      name: Log Deletion Request
      action: debug:log
      input:
        message: |
          ⚠️ DELETION REQUEST
          State Key: ${{ parameters.stateKey }}/terraform.tfstate
          Owner: ${{ parameters.owner }} (${{ parameters.ownerEmail }})
          Confirmed: ${{ parameters.confirmDeletion }}

    - id: terraform-destroy
      name: Destroy Resource
      if: ${{ parameters.confirmDeletion == true }}
      action: terraform:destroy
      input:
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: ${{ parameters.stateKey }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        ownerEmail: ${{ parameters.ownerEmail }}
        resourceOwner: ${{ parameters.ownerEmail }}
        autoApprove: true

  output:
    links:
      - title: "🔙 Back to Templates"
        url: /create
      - title: "📂 S3 State Bucket"
        url: "https://console.aws.amazon.com/s3/buckets/poc-idp-tfstate"
    text:
      - title: Status
        content: |
          ${{ parameters.confirmDeletion == true ? '✅ Resource deleted successfully' : '❌ Deletion cancelled - confirmation required' }}
