apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: resource-manager
  title: "🗑️ Delete My Resources"
  description: |
    View and delete resources you have created via Backstage.
    Resources are automatically listed from your Terraform state.
  tags:
    - terraform
    - aws
    - delete
    - management
spec:
  owner: platform-team
  type: management

  parameters:
    - title: "🗑️ Delete Resource"
      description: |
        ## 🔍 Step 1: View Your Resources

        After clicking **"Review"** below, you'll see a link to view your resources.

        ## 📝 Step 2: Fill the form below

        Enter the `type` and `name` of the resource you want to delete.

        🔒 **Security:** You can only delete resources that you own.
      required:
        - resourceType
        - resourceName
        - confirmDeletion
      properties:
        resourceType:
          title: " Resource Type"
          type: string
          enum:
            - s3
            - ec2
            - lambda
            - rds
          default: s3
          description: Type from API response (e.g., "s3", "ec2")
        resourceName:
          title: " Resource Name"
          type: string
          description: Name from API response (e.g., "my-bucket-name")
          ui:autofocus: true
          ui:placeholder: "my-bucket-name"
        confirmDeletion:
          title: " I CONFIRM I want to PERMANENTLY DELETE this resource"
          type: boolean
          default: false
          ui:widget: checkbox

  steps:
    - id: fetch-base
      name: Fetch Terraform Config
      if: ${{ parameters.confirmDeletion == true }}
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./terraform

    - id: terraform-destroy
      name: Destroy Resource
      if: ${{ parameters.confirmDeletion == true }}
      action: terraform:destroy
      input:
        terraformDir: ./terraform
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: ${{ parameters.resourceType }}/${{ user.entity.metadata.name | default('admin') }}/${{ parameters.resourceName }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        ownerEmail: ${{ user.entity.spec.profile.email | default('admin@darede.com.br') }}
        resourceOwner: ${{ user.entity.spec.profile.email | default('admin@darede.com.br') }}
        autoApprove: true

  output:
    links:
      - title: " View YOUR Resources (filtered by owner)"
        url: "/api/resources/resources?owner=${{ user.entity.metadata.name | default('admin') }}"
      - title: " Back to Templates"
        url: /create
      - title: " S3 State Bucket"
        url: "https://console.aws.amazon.com/s3/buckets/${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}"
    text:
      - title: Status
        content: |
          ${{ parameters.confirmDeletion == true ? ' Resource deleted successfully' : ' Deletion cancelled - confirmation required' }}
      - title: " Your Username"
        content: ${{ user.entity.metadata.name | default('admin') }}
