apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: resource-manager
  title: "🗑️ Delete My Resources"
  description: |
    Delete resources you have created via Backstage.
    Resources are stored in: s3://poc-idp-tfstate/{type}/{owner}/{name}/terraform.tfstate
  tags:
    - terraform
    - aws
    - delete
    - management
spec:
  owner: platform-team
  type: management

  parameters:
    - title: "📋 Your Resources"
      description: |
        ## How to find your resources

        Run this command to list your resources:
        ```bash
        aws s3 ls s3://poc-idp-tfstate/ --recursive | grep "/${{ user.entity.metadata.name | default('admin') }}/"
        ```

        Or check the [S3 Console](https://console.aws.amazon.com/s3/buckets/poc-idp-tfstate)

        ---

        **Resource path format:** `{type}/{owner}/{name}/terraform.tfstate`

        Examples:
        - `s3/admin/my-bucket/terraform.tfstate`
        - `ec2/admin/my-instance/terraform.tfstate`
        - `vpc/admin/my-vpc/terraform.tfstate`
      required:
        - resourceType
        - resourceName
        - confirmDeletion
      properties:
        resourceType:
          title: Resource Type
          type: string
          description: Type of resource to delete
          enum:
            - s3
            - ec2
            - ec2-ssm
            - vpc
            - rds
            - dynamodb
            - lambda
            - alb
            - cloudfront
            - eks
            - security-group
            - secrets
          enumNames:
            - S3 Bucket
            - EC2 Instance
            - EC2 Instance (SSM)
            - VPC
            - RDS Database
            - DynamoDB Table
            - Lambda Function
            - Application Load Balancer
            - CloudFront Distribution
            - EKS Cluster
            - Security Group
            - Secrets Manager Secret
        resourceName:
          title: Resource Name
          type: string
          description: Exact name of the resource to delete
          ui:autofocus: true
        confirmDeletion:
          title: "⚠️ I CONFIRM I want to PERMANENTLY DELETE this resource"
          type: boolean
          default: false
          ui:widget: checkbox

    - title: Owner Verification
      properties:
        owner:
          title: Owner (You)
          type: string
          default: ${{ user.entity.metadata.name | default('unknown') }}
          ui:readonly: true
        ownerEmail:
          title: Owner Email
          type: string
          default: ${{ user.entity.spec.profile.email | default('unknown@example.com') }}
          ui:readonly: true

  steps:
    - id: log-request
      name: Log Deletion Request
      action: debug:log
      input:
        message: |
          ⚠️ DELETION REQUEST
          Type: ${{ parameters.resourceType }}
          Name: ${{ parameters.resourceName }}
          Owner: ${{ parameters.owner }} (${{ parameters.ownerEmail }})
          State Key: ${{ parameters.resourceType }}/${{ parameters.owner }}/${{ parameters.resourceName }}/terraform.tfstate
          Confirmed: ${{ parameters.confirmDeletion }}

    - id: terraform-destroy
      name: Destroy Resource
      if: ${{ parameters.confirmDeletion == true }}
      action: terraform:destroy
      input:
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: ${{ parameters.resourceType }}/${{ parameters.owner }}/${{ parameters.resourceName }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        ownerEmail: ${{ parameters.ownerEmail }}
        resourceOwner: ${{ parameters.ownerEmail }}
        autoApprove: true

  output:
    links:
      - title: Back to Templates
        url: /create
      - title: S3 State Bucket
        url: "https://console.aws.amazon.com/s3/buckets/poc-idp-tfstate"
    text:
      - title: Status
        content: |
          ${{ parameters.confirmDeletion == true ? '✅ Resource deleted successfully' : '❌ Deletion cancelled - confirmation required' }}
