apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: resource-manager
  title: "🗑️ Delete My Resources"
  description: |
    View and delete resources you have created via Backstage.
    Resources are automatically listed from your Terraform state.
  tags:
    - terraform
    - aws
    - delete
    - management
spec:
  owner: platform-team
  type: management

  parameters:
    - title: " Step 1: View Your Resources"
      description: |
        Copy the URL below and paste it in your browser to see ONLY your resources.
      properties:
        yourUsername:
          title: " Your Username"
          type: string
          ui:readonly: true
          default: ${{ user.entity.metadata.name | default('unknown') }}
        resourceApiUrl:
          title: " Your Resources API (copy this URL)"
          type: string
          ui:readonly: true
          ui:widget: textarea
          ui:options:
            rows: 2
          default: "/api/resources/resources?owner=${{ user.entity.metadata.name | default('unknown') }}"

    - title: " Step 2: Delete Resource"
      description: |
        Enter the **type** and **name** from YOUR resources only.

        **You can only delete resources where owner = ${{ user.entity.metadata.name }}**

        Example API response:
        ```json
        [
          {"type": "ec2", "owner": "${{ user.entity.metadata.name }}", "name": "my-instance"}
        ]
        ```
      required:
        - resourceType
        - resourceName
        - confirmDeletion
      properties:
        resourceType:
          title: " Resource Type"
          type: string
          enum:
            - s3
            - ec2
            - lambda
            - rds
          default: s3
          description: Type from API response (e.g., "s3", "ec2")
        resourceName:
          title: " Resource Name"
          type: string
          description: Name from API response (e.g., "my-bucket-name")
          ui:autofocus: true
          ui:placeholder: "my-bucket-name"
        confirmDeletion:
          title: " I CONFIRM I want to PERMANENTLY DELETE this resource"
          type: boolean
          default: false
          ui:widget: checkbox

  steps:
    - id: fetch-base
      name: Fetch Terraform Config
      if: ${{ parameters.confirmDeletion == true }}
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./terraform

    - id: terraform-destroy
      name: Destroy Resource
      if: ${{ parameters.confirmDeletion == true }}
      action: terraform:destroy
      input:
        terraformDir: ./terraform
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: ${{ parameters.resourceType }}/${{ user.entity.metadata.name | default('admin') }}/${{ parameters.resourceName }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        ownerEmail: ${{ user.entity.spec.profile.email | default('admin@darede.com.br') }}
        resourceOwner: ${{ user.entity.spec.profile.email | default('admin@darede.com.br') }}
        autoApprove: true

  output:
    links:
      - title: "🔙 Back to Templates"
        url: /create
      - title: "📂 S3 State Bucket"
        url: "https://console.aws.amazon.com/s3/buckets/poc-idp-tfstate"
    text:
      - title: Status
        content: |
          ${{ parameters.confirmDeletion == true ? '✅ Resource deleted successfully' : '❌ Deletion cancelled - confirmation required' }}
