apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-cloudfront-s3
  title: CloudFront + S3 Static Website
  description: Create a static website with S3 bucket and CloudFront CDN distribution.
  tags: [terraform, aws, cloudfront, s3, cdn, website]
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Website Configuration
      required: [name]
      properties:
        name:
          title: Website Name
          type: string
          pattern: '^[a-z][a-z0-9-]*$'
        domainName:
          title: Custom Domain (Optional)
          type: string
          default: ""
        certificateArn:
          title: ACM Certificate ARN (Optional)
          type: string
          default: ""
          description: Required if using custom domain
        defaultRootObject:
          title: Default Root Object
          type: string
          default: index.html
        priceClass:
          title: Price Class
          type: string
          default: PriceClass_100
          enum: [PriceClass_100, PriceClass_200, PriceClass_All]
          enumNames: [North America & Europe, + Asia & Africa, All Edge Locations]
    - title: Metadata
      required: [environment]
      properties:
        environment:
          title: Environment
          type: string
          default: dev
          enum: [dev, staging, prod]
        owner:
          title: Owner
          type: string
          default: ${{ user.entity.metadata.name | default('unknown') }}
          ui:readonly: true
        ownerEmail:
          title: Owner Email
          type: string
          default: ${{ user.entity.spec.profile.email | default('unknown@example.com') }}
          ui:readonly: true
  steps:
    - id: fetch-template
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
    - id: terraform-apply
      name: Apply Terraform
      action: terraform:apply
      input:
        terraformDir: ./output
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: cloudfront/${{ parameters.owner }}/${{ parameters.name }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        variables:
          name: ${{ parameters.name }}
          domain_name: ${{ parameters.domainName }}
          certificate_arn: ${{ parameters.certificateArn }}
          default_root_object: ${{ parameters.defaultRootObject }}
          price_class: ${{ parameters.priceClass }}
          environment: ${{ parameters.environment }}
          owner: ${{ parameters.owner }}
          owner_email: ${{ parameters.ownerEmail }}
        autoApprove: true
  output:
    links:
      - title: CloudFront Console
        url: "https://console.aws.amazon.com/cloudfront/v4/home"
      - title: S3 Console
        url: "https://console.aws.amazon.com/s3/home"
      - title: View in Catalog
        entityRef: resource:default/cdn-${{ parameters.name }}
    text:
      - title: Website URL
        content: ${{ steps['terraform-apply'].output.outputs.website_url }}
      - title: S3 Bucket
        content: ${{ steps['terraform-apply'].output.outputs.bucket_name }}
