# RDS Database Instance
# Generated by Backstage Template

terraform {
  required_version = ">= 1.0"

  backend "s3" {}

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0"
    }
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      ManagedBy   = "Terraform"
      CreatedBy   = "Backstage"
      Owner       = var.owner
      OwnerEmail  = var.owner_email
      Environment = var.environment
      Project     = var.db_identifier
    }
  }
}

# Variables
variable "region" {
  type    = string
  default = "us-east-1"
}

variable "db_identifier" {
  type = string
}

variable "engine" {
  type    = string
  default = "postgres"
}

variable "engine_version" {
  type    = string
  default = "15.4"
}

variable "instance_class" {
  type    = string
  default = "db.t3.micro"
}

variable "allocated_storage" {
  type    = number
  default = 20
}

variable "max_allocated_storage" {
  type    = number
  default = 100
}

variable "storage_type" {
  type    = string
  default = "gp3"
}

variable "db_name" {
  type = string
}

variable "db_username" {
  type    = string
  default = "admin"
}

variable "vpc_id" {
  type = string
}

variable "subnet_ids" {
  type = list(string)
}

variable "allowed_cidr_blocks" {
  type    = list(string)
  default = []
}

variable "allowed_security_groups" {
  type    = list(string)
  default = []
}

variable "multi_az" {
  type    = bool
  default = false
}

variable "publicly_accessible" {
  type    = bool
  default = false
}

variable "backup_retention_period" {
  type    = number
  default = 7
}

variable "backup_window" {
  type    = string
  default = "03:00-04:00"
}

variable "maintenance_window" {
  type    = string
  default = "Mon:04:00-Mon:05:00"
}

variable "deletion_protection" {
  type    = bool
  default = false
}

variable "skip_final_snapshot" {
  type    = bool
  default = true
}

variable "performance_insights_enabled" {
  type    = bool
  default = false
}

variable "environment" {
  type    = string
  default = "dev"
}

variable "owner" {
  type = string
}

variable "owner_email" {
  type = string
}

# Random password for DB
resource "random_password" "db_password" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# Store password in Secrets Manager
resource "aws_secretsmanager_secret" "db_credentials" {
  name                    = "${var.db_identifier}-credentials"
  description             = "RDS credentials for ${var.db_identifier}"
  recovery_window_in_days = 0

  tags = {
    Name = "${var.db_identifier}-credentials"
  }
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_password.result
    engine   = var.engine
    host     = aws_db_instance.main.address
    port     = aws_db_instance.main.port
    dbname   = var.db_name
  })
}

# DB Subnet Group
resource "aws_db_subnet_group" "main" {
  name        = "${var.db_identifier}-subnet-group"
  description = "Subnet group for ${var.db_identifier}"
  subnet_ids  = var.subnet_ids

  tags = {
    Name = "${var.db_identifier}-subnet-group"
  }
}

# Security Group
resource "aws_security_group" "db_sg" {
  name        = "${var.db_identifier}-sg"
  description = "Security group for RDS ${var.db_identifier}"
  vpc_id      = var.vpc_id

  tags = {
    Name = "${var.db_identifier}-sg"
  }
}

# Ingress rules for CIDR blocks
resource "aws_security_group_rule" "db_ingress_cidr" {
  count             = length(var.allowed_cidr_blocks) > 0 ? 1 : 0
  type              = "ingress"
  from_port         = local.db_port
  to_port           = local.db_port
  protocol          = "tcp"
  cidr_blocks       = var.allowed_cidr_blocks
  security_group_id = aws_security_group.db_sg.id
  description       = "Allow DB access from CIDR blocks"
}

# Ingress rules for Security Groups
resource "aws_security_group_rule" "db_ingress_sg" {
  for_each                 = toset(var.allowed_security_groups)
  type                     = "ingress"
  from_port                = local.db_port
  to_port                  = local.db_port
  protocol                 = "tcp"
  source_security_group_id = each.value
  security_group_id        = aws_security_group.db_sg.id
  description              = "Allow DB access from security group ${each.value}"
}

locals {
  db_port = var.engine == "postgres" ? 5432 : (var.engine == "mysql" ? 3306 : 5432)
}

# Parameter Group
resource "aws_db_parameter_group" "main" {
  name        = "${var.db_identifier}-params"
  family      = "${var.engine}${split(".", var.engine_version)[0]}"
  description = "Parameter group for ${var.db_identifier}"

  tags = {
    Name = "${var.db_identifier}-params"
  }

  lifecycle {
    create_before_destroy = true
  }
}

# RDS Instance
resource "aws_db_instance" "main" {
  identifier     = var.db_identifier
  engine         = var.engine
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = var.storage_type
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db_password.result

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.db_sg.id]
  parameter_group_name   = aws_db_parameter_group.main.name

  multi_az            = var.multi_az
  publicly_accessible = var.publicly_accessible

  backup_retention_period = var.backup_retention_period
  backup_window           = var.backup_window
  maintenance_window      = var.maintenance_window

  deletion_protection = var.deletion_protection
  skip_final_snapshot = var.skip_final_snapshot

  performance_insights_enabled = var.performance_insights_enabled

  tags = {
    Name = var.db_identifier
  }
}

# Outputs
output "db_instance_id" {
  value = aws_db_instance.main.id
}

output "db_instance_arn" {
  value = aws_db_instance.main.arn
}

output "db_endpoint" {
  value = aws_db_instance.main.endpoint
}

output "db_address" {
  value = aws_db_instance.main.address
}

output "db_port" {
  value = aws_db_instance.main.port
}

output "db_name" {
  value = aws_db_instance.main.db_name
}

output "secret_arn" {
  value = aws_secretsmanager_secret.db_credentials.arn
}

output "security_group_id" {
  value = aws_security_group.db_sg.id
}

output "connection_string" {
  value     = "${var.engine}://${var.db_username}:<password>@${aws_db_instance.main.endpoint}/${var.db_name}"
  sensitive = true
}
