################################################################################
# Keycloak Realm Configuration ConfigMap
# Contains the platform realm configuration for import
# This file is generated by scripts/render-templates.sh
# DO NOT EDIT MANUALLY - edit realm-config.json.tpl instead
################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: keycloak
data:
  realm.json: REALM_CONFIG_PLACEHOLDER
