apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-credentials
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: github-app-credentials
    creationPolicy: Owner
  data:
    - secretKey: appId
      remoteRef:
        key: idp-poc-darede-cluster-github-app-credentials
        property: appId
    - secretKey: clientId
      remoteRef:
        key: idp-poc-darede-cluster-github-app-credentials
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: idp-poc-darede-cluster-github-app-credentials
        property: clientSecret
    - secretKey: webhookSecret
      remoteRef:
        key: idp-poc-darede-cluster-github-app-credentials
        property: webhookSecret
    - secretKey: privateKey
      remoteRef:
        key: idp-poc-darede-cluster-github-app-credentials
        property: privateKey
