apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-lister
  namespace: backstage
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::948881762705:role/backstage-terraform-irsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-manager
  namespace: backstage
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-lister-configmap
  namespace: backstage
subjects:
- kind: ServiceAccount
  name: resource-lister
  namespace: backstage
roleRef:
  kind: Role
  name: configmap-manager
  apiGroup: rbac.authorization.k8s.io
