apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-lister
  namespace: backstage
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::948881762705:role/backstage-terraform-irsa
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-lister-script
  namespace: backstage
data:
  list-resources.sh: |
    #!/bin/sh
    set -e

    BUCKET="${S3_BUCKET:-poc-idp-tfstate}"
    REGION="${AWS_REGION:-us-east-1}"
    OUTPUT_FILE="/tmp/resources.json"

    echo "Listing resources from s3://${BUCKET}..."

    # List all terraform state files
    aws s3 ls "s3://${BUCKET}/" --recursive --region "$REGION" | \
      grep "terraform.tfstate$" | \
      awk '{print $4}' | \
      while read state_key; do
        # Parse resource info from state key
        # Format: type/owner/name/terraform.tfstate
        resource_type=$(echo "$state_key" | cut -d'/' -f1)
        resource_owner=$(echo "$state_key" | cut -d'/' -f2)
        resource_name=$(echo "$state_key" | cut -d'/' -f3)

        # Get state file metadata
        last_modified=$(aws s3api head-object --bucket "$BUCKET" --key "$state_key" --region "$REGION" --query 'LastModified' --output text 2>/dev/null || echo "unknown")

        echo "{\"type\":\"$resource_type\",\"owner\":\"$resource_owner\",\"name\":\"$resource_name\",\"stateKey\":\"${resource_type}/${resource_owner}/${resource_name}\",\"lastModified\":\"$last_modified\"}"
      done | jq -s '.' > "$OUTPUT_FILE"

    echo "Found $(cat $OUTPUT_FILE | jq 'length') resources"
    cat "$OUTPUT_FILE"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: resource-lister
  namespace: backstage
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: resource-lister
          restartPolicy: OnFailure
          containers:
          - name: list-resources
            image: amazon/aws-cli:2.15.17
            command: ["/bin/sh", "/scripts/list-resources.sh"]
            env:
            - name: S3_BUCKET
              value: "poc-idp-tfstate"
            - name: AWS_REGION
              value: "us-east-1"
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: output
              mountPath: /tmp
          - name: update-configmap
            image: bitnami/kubectl:1.28
            command: ["/bin/sh", "-c"]
            args:
            - |
              kubectl create configmap backstage-resources \
                --from-file=resources.json=/tmp/resources.json \
                --dry-run=client -o yaml | \
              kubectl apply -f -
            volumeMounts:
            - name: output
              mountPath: /tmp
          volumes:
          - name: scripts
            configMap:
              name: resource-lister-script
              defaultMode: 0755
          - name: output
            emptyDir: {}
