apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-eks-cluster
  title: EKS Cluster
  description: Create EKS cluster with managed node groups (On-Demand or Spot) using Terraform
  tags: [aws, eks, kubernetes, terraform]
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Cluster Configuration
      required: [name, environment, kubernetesVersion]
      properties:
        name:
          title: Cluster Name
          type: string
          pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
        environment:
          title: Environment
          type: string
          enum: [poc, dev, staging, prod]
          default: poc
        kubernetesVersion:
          title: Kubernetes Version
          type: string
          enum: ["1.33", "1.34"]
          default: "1.31"
          description: "Versão do Kubernetes (1.34 é a mais recente)"

    - title: Node Group Configuration
      required: [nodeInstanceType, capacityType]
      properties:
        capacityType:
          title: Capacity Type
          type: string
          enum: [ON_DEMAND, SPOT]
          enumNames: ["On-Demand (custo fixo, alta disponibilidade)", "Spot (até 90% mais barato, pode ser interrompido)"]
          default: ON_DEMAND
          description: "Spot é mais barato mas as instâncias podem ser terminadas pela AWS"
        nodeInstanceType:
          title: Node Instance Type
          type: string
          default: t3.medium
          enum: [t3.small, t3.medium, t3.large, t3.xlarge, m5.large, m5.xlarge, m5.2xlarge, c5.large, c5.xlarge]
          enumNames: ["t3.small (2 vCPU, 2GB)", "t3.medium (2 vCPU, 4GB)", "t3.large (2 vCPU, 8GB)", "t3.xlarge (4 vCPU, 16GB)", "m5.large (2 vCPU, 8GB)", "m5.xlarge (4 vCPU, 16GB)", "m5.2xlarge (8 vCPU, 32GB)", "c5.large (2 vCPU, 4GB)", "c5.xlarge (4 vCPU, 8GB)"]
        nodeMinSize:
          title: Minimum Nodes
          type: integer
          default: 1
          minimum: 1
          maximum: 10
        nodeMaxSize:
          title: Maximum Nodes
          type: integer
          default: 4
          minimum: 1
          maximum: 20
        nodeDesiredSize:
          title: Desired Nodes
          type: integer
          default: 2
          minimum: 1
          maximum: 10

    - title: Network Configuration
      properties:
        vpcCidr:
          title: VPC CIDR
          type: string
          default: "10.0.0.0/16"
          description: "CIDR block para a VPC do cluster"
        enablePublicAccess:
          title: Enable Public API Access
          type: boolean
          default: true
          description: "Permitir acesso ao API server do cluster pela internet"

    - title: Tags
      properties:
        tags:
          title: Custom Tags
          type: array
          items:
            type: object
            required: [key, value]
            properties:
              key:
                title: Key
                type: string
              value:
                title: Value
                type: string
          ui:options:
            addable: true
            removable: true
  steps:
    - id: fetch
      name: Generate Terraform Configuration
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          name: ${{ parameters.name }}
          environment: ${{ parameters.environment }}
          kubernetesVersion: ${{ parameters.kubernetesVersion }}
          capacityType: ${{ parameters.capacityType }}
          nodeInstanceType: ${{ parameters.nodeInstanceType }}
          nodeMinSize: ${{ parameters.nodeMinSize }}
          nodeMaxSize: ${{ parameters.nodeMaxSize }}
          nodeDesiredSize: ${{ parameters.nodeDesiredSize }}
          vpcCidr: ${{ parameters.vpcCidr }}
          enablePublicAccess: ${{ parameters.enablePublicAccess }}
          # Auto-populate owner from Keycloak user identity
          owner: ${{ user.entity.metadata.name | default('unknown') }}
          ownerEmail: ${{ user.entity.spec.profile.email | default('') }}
          tags: ${{ parameters.tags }}
          githubOrg: ${{ env.GITHUB_ORG | default('darede-labs') }}
          infraRepo: ${{ env.INFRA_REPO | default('infrastructureidp') }}
          tfBackendBucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          tfBackendRegion: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{ env.GITHUB_ORG | default('darede-labs') }}&repo=${{ env.INFRA_REPO | default('infrastructureidp') }}
        branchName: infra/eks-${{ user.entity.metadata.name | default('user') }}-${{ parameters.name }}
        title: 'feat(eks): Create cluster ${{ parameters.name }} for ${{ user.entity.metadata.name | default("user") }}'
        description: |
          ## ☸️ New EKS Cluster Request
          | Property | Value |
          |----------|-------|
          | **Name** | `${{ parameters.name }}` |
          | **K8s Version** | `${{ parameters.kubernetesVersion }}` |
          | **Capacity** | `${{ parameters.capacityType }}` |
          | **Instance** | `${{ parameters.nodeInstanceType }}` |
          | **Nodes** | `${{ parameters.nodeMinSize }}-${{ parameters.nodeMaxSize }}` |
          ### Owner Enforcement
          Only `${{ user.entity.metadata.name | default("unknown") }}` can delete this resource.
          ---
          *Created via Backstage by ${{ user.entity.metadata.name | default("unknown") }}*
        sourcePath: ./output
        # User-segregated path: eks/{username}/{resource_name}
        targetPath: platform/terraform/stacks/eks/${{ user.entity.metadata.name | default('shared') }}/${{ parameters.name }}
  output:
    links:
      - title: Pull Request
        url: ${{ steps['publish'].output.remoteUrl }}
