apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.clusterName }}
  description: EKS Cluster provisioned via Crossplane
  annotations:
    aws.amazon.com/region: ${{ values.region }}
    aws.amazon.com/resource-type: eks-cluster
    aws.amazon.com/kubernetes-version: ${{ values.kubernetesVersion }}
    backstage.io/managed-by-location: url:https://github.com/darede-labs/infrastructure/tree/main/eks-clusters/${{ values.clusterName }}
  tags:
    - aws
    - eks
    - kubernetes
    - infrastructure
  links:
    - url: https://console.aws.amazon.com/eks/home?region=${{ values.region }}#/clusters/${{ values.clusterName }}
      title: AWS Console
      icon: cloud
spec:
  type: eks-cluster
  owner: ${{ values.owner }}
  lifecycle: production
  system: platform
  dependsOn:
    - resource:crossplane-aws-provider
  providesApis:
    - kubernetes-api
