apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-destroy-resource
  title: "🗑️ Destruir Recurso AWS"
  description: Remove um recurso AWS criado via plataforma (GitOps com Atlantis)
  tags:
    - aws
    - terraform
    - destroy
    - cleanup
  links:
    - url: https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks
      title: 📂 Ver Recursos Existentes
      icon: github
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Selecionar Recurso para Destruir
      description: |
        ## 📂 Recursos Existentes
        Clique nos links para ver os recursos disponíveis:
        - [S3 Buckets](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/s3)
        - [EC2 Instances](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/ec2)
        - [Security Groups](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/security-group)
        - [VPCs](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/vpc)
        - [EKS Clusters](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/eks)
        - [Secrets](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/secrets)
      required:
        - resourceType
        - resourceName
        - confirmDestroy
      properties:
        resourceType:
          title: Tipo de Recurso
          type: string
          enum:
            - s3
            - ec2
            - security-group
            - vpc
            - eks
            - secrets
          enumNames:
            - S3 Bucket
            - EC2 Instance
            - Security Group
            - VPC
            - EKS Cluster
            - Secrets Manager
        resourceName:
          title: Nome do Recurso
          type: string
          description: Nome exato do recurso (pasta) a ser destruído
        confirmDestroy:
          title: "⚠️ CONFIRMO que desejo DESTRUIR este recurso permanentemente"
          type: boolean
          default: false
          ui:widget: checkbox

  steps:
    - id: fetch-skeleton
      name: Gerar configuração de destruição
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          resourceType: ${{ parameters.resourceType }}
          resourceName: ${{ parameters.resourceName }}
          tfBackendBucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          tfBackendRegion: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}

    - id: publish
      name: Criar Pull Request de Destruição
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{ env.GITHUB_ORG | default('darede-labs') }}&repo=${{ env.INFRA_REPO | default('infrastructureidp') }}
        branchName: destroy/${{ parameters.resourceType }}-${{ parameters.resourceName }}
        title: "🗑️ DESTROY: ${{ parameters.resourceType }}/${{ parameters.resourceName }}"
        description: |
          ## ⚠️ DESTRUIÇÃO DE RECURSO

          | Property | Value |
          |----------|-------|
          | **Tipo** | `${{ parameters.resourceType }}` |
          | **Nome** | `${{ parameters.resourceName }}` |

          ### 🔄 Fluxo Automático
          1. Este PR **substitui** o main.tf por uma versão vazia (sem recursos)
          2. Atlantis detecta a mudança e planeja a destruição dos recursos
          3. Após apply bem-sucedido (destroy), o PR é mergeado automaticamente

          ### ⚠️ ATENÇÃO
          - Esta ação é **IRREVERSÍVEL**
          - O recurso será **permanentemente deletado** da AWS
          - Buckets S3 com objetos e Secrets podem demorar para serem removidos

          ---
          *Solicitação de destruição via Backstage*
        sourcePath: ./output
        targetPath: platform/terraform/stacks/${{ parameters.resourceType }}/${{ parameters.resourceName }}
        gitCommitMessage: "destroy(${{ parameters.resourceType }}): remove resources from ${{ parameters.resourceName }}"

  output:
    links:
      - title: Pull Request de Destruição
        url: ${{ steps['publish'].output.remoteUrl }}
