apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-destroy-resource
  title: "🗑️ Destruir Recurso AWS"
  description: Remove um recurso AWS criado via plataforma (GitOps com Atlantis)
  tags:
    - aws
    - terraform
    - destroy
    - cleanup
  links:
    - url: https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks
      title: 📂 Ver Recursos Existentes
      icon: github
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Selecionar Recurso
      description: |
        📂 **Veja os recursos existentes antes de destruir:**
        - [S3 Buckets](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/s3)
        - [EC2 Instances](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/ec2)
        - [Security Groups](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/security-group)
        - [VPCs](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/vpc)
        - [EKS Clusters](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/eks)
        - [Secrets](https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks/secrets)
      required:
        - resourceType
        - resourceName
      properties:
        resourceType:
          title: Tipo de Recurso
          type: string
          enum:
            - s3
            - ec2
            - security-group
            - vpc
            - eks
            - secrets
          enumNames:
            - S3 Bucket
            - EC2 Instance
            - Security Group
            - VPC
            - EKS Cluster
            - Secrets Manager
        resourceName:
          title: Nome do Recurso
          type: string
          description: Nome exato do recurso a ser destruído (veja os links acima)
        confirmDestroy:
          title: "⚠️ Confirmo que desejo DESTRUIR este recurso permanentemente"
          type: boolean
          default: false

  steps:
    - id: fetch
      name: Gerar arquivo de destruição
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          resourceType: ${{ parameters.resourceType }}
          resourceName: ${{ parameters.resourceName }}

    - id: publish
      name: Criar Pull Request de Destruição
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{ parameters.githubOrg | default('darede-labs') }}&repo=${{ parameters.infraRepo | default('infrastructureidp') }}
        branchName: destroy/${{ parameters.resourceType }}-${{ parameters.resourceName }}
        title: "🗑️ DESTROY: ${{ parameters.resourceType }}/${{ parameters.resourceName }}"
        description: |
          ## ⚠️ ATENÇÃO: Destruição de Recurso

          | Property | Value |
          |----------|-------|
          | **Tipo** | `${{ parameters.resourceType }}` |
          | **Nome** | `${{ parameters.resourceName }}` |

          ### ⚡ Ação Requerida
          1. Atlantis executará `terraform plan -destroy` automaticamente
          2. Revise o plano de destruição abaixo
          3. **CUIDADO**: Esta ação é IRREVERSÍVEL
          4. Se confirmar, comente `/atlantis apply`

          ---
          *Solicitação de destruição via Backstage*
        sourcePath: ./output
        targetPath: platform/terraform/stacks/${{ parameters.resourceType }}/${{ parameters.resourceName }}

  output:
    links:
      - title: Pull Request de Destruição
        url: ${{ steps['publish'].output.remoteUrl }}
