apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-destroy-resource
  title: "🗑️ Safe Destroy - AWS Resource"
  description: Safely remove an AWS resource you own (GitOps with Atlantis + Owner Enforcement)
  tags:
    - aws
    - terraform
    - destroy
    - cleanup
    - safe-deletion
  links:
    - url: https://github.com/darede-labs/infrastructureidp/tree/main/platform/terraform/stacks
      title: 📂 View Existing Resources
      icon: github
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Select Resource to Destroy
      description: |
        ## 🔒 Owner Enforcement Active
        You can only delete resources that YOU created. The system will verify ownership before allowing destruction.

        ## 📂 Your Resources
        Resources are organized by owner: `{resource_type}/{your_username}/{resource_name}`
      required:
        - resourceType
        - resourceName
        - confirmDestroy
      properties:
        resourceType:
          title: Resource Type
          type: string
          enum:
            - s3
            - ec2
            - security-group
            - vpc
            - eks
            - secrets
          enumNames:
            - S3 Bucket
            - EC2 Instance
            - Security Group
            - VPC
            - EKS Cluster
            - Secrets Manager
        resourceName:
          title: Resource Name
          type: string
          description: Exact name of the resource (folder) to destroy
        confirmDestroy:
          title: "⚠️ I CONFIRM I want to PERMANENTLY DESTROY this resource"
          type: boolean
          default: false
          ui:widget: checkbox

  steps:
    - id: fetch-skeleton
      name: Generate destroy configuration
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          resourceType: ${{ parameters.resourceType }}
          resourceName: ${{ parameters.resourceName }}
          # Auto-populate owner from Keycloak user identity for verification
          requestingUser: ${{ (user.ref | default('user:default/unknown') | parseEntityRef).name | default("unknown") }}
          tfBackendBucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          tfBackendRegion: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}

    - id: publish
      name: Create Destroy Pull Request (Owner-Enforced)
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{ env.GITHUB_ORG | default('darede-labs') }}&repo=${{ env.INFRA_REPO | default('infrastructureidp') }}
        branchName: destroy/${{ (user.ref | default('user:default/user') | parseEntityRef).name | default("user") }}-${{ parameters.resourceType }}-${{ parameters.resourceName }}
        title: "DESTROY: ${{ parameters.resourceType }}/${{ (user.ref | default('user:default/user') | parseEntityRef).name | default('user') }}/${{ parameters.resourceName }}"
        description: |
          ## ⚠️ RESOURCE DESTRUCTION REQUEST

          | Property | Value |
          |----------|-------|
          | **Type** | `${{ parameters.resourceType }}` |
          | **Name** | `${{ parameters.resourceName }}` |
          | **Requesting User** | `${{ (user.ref | default('user:default/unknown') | parseEntityRef).name | default("unknown") }}` |

          ### Owner Enforcement
          This PR targets the path: `${{ parameters.resourceType }}/${{ (user.ref | default('user:default/user') | parseEntityRef).name | default("user") }}/${{ parameters.resourceName }}`

          **Only resources owned by `${{ (user.ref | default('user:default/unknown') | parseEntityRef).name | default("unknown") }}` can be destroyed.**

          Atlantis will verify the `Owner` tag in Terraform state matches the requesting user before allowing destroy.

          ### 🔄 Automated Flow
          1. This PR replaces main.tf with an empty version (no resources)
          2. Atlantis detects the change and plans the destruction
          3. After successful apply (destroy), PR is auto-merged

          ### ⚠️ WARNING
          - This action is **IRREVERSIBLE**
          - Resource will be **permanently deleted** from AWS

          ---
          *Destruction request via Backstage by ${{ (user.ref | default('user:default/unknown') | parseEntityRef).name | default("unknown") }}*
        sourcePath: ./output
        # Owner-enforced path: {resource_type}/{username}/{resource_name}
        targetPath: platform/terraform/stacks/${{ parameters.resourceType }}/${{ (user.ref | default('user:default/shared') | parseEntityRef).name | default('shared') }}/${{ parameters.resourceName }}
        gitCommitMessage: 'destroy(${{ parameters.resourceType }}): remove ${{ parameters.resourceName }} [owner: ${{ (user.ref | default('user:default/unknown') | parseEntityRef).name | default("unknown") }}]'

  output:
    links:
      - title: Pull Request de Destruição
        url: ${{ steps['publish'].output.remoteUrl }}
