apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  # Template for nodes launched by this NodePool
  template:
    metadata:
      # Labels applied to all nodes
      labels:
        karpenter.sh/capacity-type: spot
        workload-type: general

    spec:
      # Node class reference (defines AWS-specific configuration)
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default

      # Taints for workload isolation (none for default pool)
      taints: []

      # Startup taints removed after node is ready
      startupTaints: []

      # Requirements for node selection
      requirements:
        # Capacity type: prefer spot for cost savings
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]

        # Architecture: only x86_64
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        # Operating system: only linux
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]

        # Instance category: general purpose (t-series)
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]

        # Instance generation: 2, 3, or 3a
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]

        # Specific instance types (from config.yaml)
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3a.medium", "t3.medium", "t2.medium"]

  # Limits for this NodePool
  limits:
    cpu: "20"      # Maximum 20 vCPUs across all nodes in this pool
    memory: 80Gi   # Maximum 80GB RAM across all nodes in this pool

  # Disruption settings (consolidation, expiration, etc)
  disruption:
    # Consolidation: Replace underutilized nodes with cheaper/smaller ones
    consolidationPolicy: WhenEmptyOrUnderutilized

    # Consolidate after 30 seconds of being empty
    consolidateAfter: 30s

    # Budget for disruptions (max 10% of nodes can be disrupted at once)
    budgets:
      - nodes: "10%"

  # Weight for scheduling priority (higher = preferred)
  weight: 10
