apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-security-group
  title: Security Group
  description: Create an AWS Security Group with custom inbound/outbound rules using Terraform
  tags:
    - aws
    - security-group
    - terraform
    - network
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Security Group Configuration
      required:
        - name
        - environment
        - vpcId
      properties:
        name:
          title: Security Group Name
          type: string
          pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
        vpcId:
          title: VPC ID
          type: string
          description: "VPC ID onde o security group será criado (ex: vpc-0123456789abcdef0)"
        description:
          title: Description
          type: string
          default: Managed by Terraform via Backstage
        environment:
          title: Environment
          type: string
          enum: [poc, dev, staging, prod]
          default: poc
        owner:
          title: Owner
          type: string
          default: platform-team

    - title: Inbound Rules (Ingress)
      description: |
        Defina as regras de entrada. Exemplos de portas:
        - **22**: SSH
        - **80**: HTTP
        - **443**: HTTPS
        - **3306**: MySQL
        - **5432**: PostgreSQL
        - **6379**: Redis
        - **27017**: MongoDB
        - **8080-8090**: Range de portas
      properties:
        ingressRules:
          title: Regras de Entrada (Inbound)
          type: array
          description: "Adicione regras para tráfego de entrada"
          items:
            type: object
            required: [fromPort, toPort, protocol, cidrBlocks, description]
            properties:
              fromPort:
                title: Porta Inicial
                type: integer
                description: "Porta inicial (ex: 22, 80, 443, 8080)"
              toPort:
                title: Porta Final
                type: integer
                description: "Porta final (igual à inicial para porta única, ou maior para range)"
              protocol:
                title: Protocolo
                type: string
                enum: [tcp, udp, icmp, "-1"]
                enumNames: [TCP, UDP, ICMP, "All Traffic"]
                default: tcp
              cidrBlocks:
                title: CIDR Blocks
                type: string
                description: "IPs permitidos (ex: 0.0.0.0/0 para todos, 10.0.0.0/8 para rede interna)"
                default: "0.0.0.0/0"
              description:
                title: Descrição da Regra
                type: string
                description: "Descreva o propósito desta regra"
          ui:options:
            addable: true
            removable: true
            orderable: true

    - title: Outbound Rules (Egress)
      description: |
        Defina as regras de saída. Por padrão, todo tráfego de saída é permitido.
        Adicione regras apenas se precisar restringir.
      properties:
        egressRules:
          title: Regras de Saída (Outbound)
          type: array
          description: "Deixe vazio para permitir todo tráfego de saída, ou adicione regras específicas"
          items:
            type: object
            required: [fromPort, toPort, protocol, cidrBlocks, description]
            properties:
              fromPort:
                title: Porta Inicial
                type: integer
              toPort:
                title: Porta Final
                type: integer
              protocol:
                title: Protocolo
                type: string
                enum: [tcp, udp, icmp, "-1"]
                enumNames: [TCP, UDP, ICMP, "All Traffic"]
                default: tcp
              cidrBlocks:
                title: CIDR Blocks
                type: string
                default: "0.0.0.0/0"
              description:
                title: Descrição
                type: string
          ui:options:
            addable: true
            removable: true

    - title: Tags
      properties:
        tags:
          title: Custom Tags
          type: array
          items:
            type: object
            required: [key, value]
            properties:
              key:
                title: Key
                type: string
              value:
                title: Value
                type: string
          ui:options:
            addable: true
            removable: true

  steps:
    - id: fetch
      name: Generate Terraform Configuration
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          name: ${{ parameters.name }}
          vpcId: ${{ parameters.vpcId }}
          description: ${{ parameters.description }}
          environment: ${{ parameters.environment }}
          owner: ${{ parameters.owner }}
          ingressRules: ${{ parameters.ingressRules }}
          egressRules: ${{ parameters.egressRules }}
          tags: ${{ parameters.tags }}
          githubOrg: ${{ env.GITHUB_ORG | default('darede-labs') }}
          infraRepo: ${{ env.INFRA_REPO | default('infrastructureidp') }}
          tfBackendBucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          tfBackendRegion: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}

    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{ env.GITHUB_ORG | default('darede-labs') }}&repo=${{ env.INFRA_REPO | default('infrastructureidp') }}
        branchName: infra/sg-${{ parameters.name }}
        title: 'feat(sg): Create security group ${{ parameters.name }}'
        description: |
          ## 🛡️ New Security Group Request

          | Property | Value |
          |----------|-------|
          | **Name** | `${{ parameters.name }}` |
          | **VPC** | `${{ parameters.vpcId }}` |
          | **Inbound Rules** | `${{ parameters.ingressRules | length }}` |
          | **Outbound Rules** | `${{ parameters.egressRules | length }}` |

          ---
          *Created via Backstage*
        sourcePath: ./output
        targetPath: platform/terraform/stacks/security-group/${{ parameters.name }}

  output:
    links:
      - title: Pull Request
        url: ${{ steps['publish'].output.remoteUrl }}
