apiVersion: platform.darede.io/v1alpha1
kind: RDSInstanceClaim
metadata:
  name: my-app-db-p
  namespace: default
spec:
  size: P
  engine: postgres
  databaseName: myapp
  masterUsername: admin
  # IMPORTANT: Replace with actual subnet IDs from your VPC
  # Get from: terraform output -raw vpc_private_subnets (or similar)
  subnetIds:
    - subnet-xxxxxxxx  # Replace with actual subnet ID from AZ 1
    - subnet-yyyyyyyy  # Replace with actual subnet ID from AZ 2
  # IMPORTANT: Replace with actual security group ID
  # Should allow access from EKS nodes to port 5432 (PostgreSQL) or 3306 (MySQL)
  vpcSecurityGroupIds:
    - sg-zzzzzzzz  # Replace with actual security group ID
  publiclyAccessible: false
  backupRetentionPeriod: 7
  multiAZ: false
  storageEncrypted: true
  writeConnectionSecretToRef:
    name: my-app-db-secret
    namespace: default
  tags:
    environment: development
    team: platform
    application: my-app
    size: P
