apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-ec2-instance
  title: EC2 Instance
  description: Create an EC2 instance using Terraform and Atlantis (GitOps)
  tags:
    - aws
    - ec2
    - terraform
    - compute
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Instance Configuration
      required:
        - name
        - instanceType
        - environment
      properties:
        name:
          title: Instance Name
          type: string
          pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
        instanceType:
          title: Instance Type
          type: string
          default: t3.micro
          enum: [t3.micro, t3.small, t3.medium, t3.large, m5.large, m5.xlarge]
        environment:
          title: Environment
          type: string
          enum: [poc, dev, staging, prod]
          default: poc
        amiType:
          title: AMI Type
          type: string
          default: amazon-linux-2023
          enum: [amazon-linux-2023, amazon-linux-2, ubuntu-22.04]
        rootVolumeSize:
          title: Root Volume Size (GB)
          type: integer
          default: 20
          minimum: 8
          maximum: 500

    - title: Network Configuration
      required:
        - subnetType
      properties:
        subnetType:
          title: Subnet Type
          type: string
          default: private
          enum: [private, public]
          enumNames: ["Private Subnet (recommended)", "Public Subnet (internet-facing)"]
        subnetId:
          title: Subnet ID (optional - leave empty for default VPC)
          type: string
          description: "Ex: subnet-0123456789abcdef0"
        securityGroupIds:
          title: Security Group IDs
          type: array
          items:
            type: string
          description: "Ex: sg-0123456789abcdef0 (leave empty to create new)"
          ui:options:
            addable: true
            removable: true

    - title: Access Configuration
      properties:
        keyPairName:
          title: SSH Key Pair Name
          type: string
          description: "Existing EC2 Key Pair name for SSH access"
        associatePublicIp:
          title: Associate Public IP
          type: boolean
          default: false
          description: "Only for public subnets"
        owner:
          title: Owner
          type: string
          default: platform-team

  steps:
    - id: fetch
      name: Generate Terraform Configuration
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          name: ${{ parameters.name }}
          instanceType: ${{ parameters.instanceType }}
          environment: ${{ parameters.environment }}
          amiType: ${{ parameters.amiType }}
          rootVolumeSize: ${{ parameters.rootVolumeSize }}
          subnetType: ${{ parameters.subnetType }}
          subnetId: ${{ parameters.subnetId }}
          securityGroupIds: ${{ parameters.securityGroupIds }}
          keyPairName: ${{ parameters.keyPairName }}
          associatePublicIp: ${{ parameters.associatePublicIp }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=darede-labs&repo=infrastructureidp
        branchName: infra/ec2-${{ parameters.name }}
        title: 'feat(ec2): Create instance ${{ parameters.name }}'
        description: |
          ## 🖥️ New EC2 Instance Request

          | Property | Value |
          |----------|-------|
          | **Name** | `${{ parameters.name }}` |
          | **Type** | `${{ parameters.instanceType }}` |
          | **AMI** | `${{ parameters.amiType }}` |
          | **Subnet** | `${{ parameters.subnetType }}` |
          | **Key Pair** | `${{ parameters.keyPairName }}` |
          | **Environment** | `${{ parameters.environment }}` |

          ---
          *Created via Backstage*
        sourcePath: ./output
        targetPath: platform/terraform/stacks/ec2/${{ parameters.name }}

  output:
    links:
      - title: Pull Request
        url: ${{ steps['publish'].output.remoteUrl }}
