apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s3-${{ values.name }}
  description: "S3 Bucket: ${{ values.name }} (Environment: ${{ values.environment }})"
  annotations:
    terraform.io/backend: s3
    terraform.io/state-key: s3/${{ values.owner }}/${{ values.name }}/terraform.tfstate
    terraform.io/state-bucket: ${{ values.tfBackendBucket }}
    terraform.io/state-region: ${{ values.tfBackendRegion }}
  links:
    - url: https://console.aws.amazon.com/s3/buckets/${{ values.name }}
      title: "AWS S3 Console"
      icon: cloud
    - url: https://s3.console.aws.amazon.com/s3/object/${{ values.tfBackendBucket }}?prefix=s3/${{ values.owner }}/${{ values.name }}/
      title: "Terraform State"
      icon: dashboard
  tags:
    - aws
    - s3
    - terraform
    - ${{ values.environment }}
spec:
  type: s3-bucket
  lifecycle: ${{ values.environment }}
  owner: ${{ values.owner }}
