apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-ec2-ssm
  title: EC2 Instance with SSM Access
  description: |
    Create an EC2 instance with SSM Session Manager access (no SSH key required).
    Includes IAM Role, Instance Profile, and Security Group configured for SSM.
  tags:
    - terraform
    - aws
    - ec2
    - ssm
    - infrastructure
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Instance Configuration
      required:
        - name
        - instanceType
        - vpcId
        - subnetId
      properties:
        name:
          title: Instance Name
          type: string
          description: Name for the EC2 instance
          pattern: '^[a-z][a-z0-9-]*$'
          ui:autofocus: true
        instanceType:
          title: Instance Type
          type: string
          description: EC2 instance type
          default: t3.micro
          enum:
            - t3.nano
            - t3.micro
            - t3.small
            - t3.medium
            - t3.large
            - t3.xlarge
            - t3.2xlarge
            - m5.large
            - m5.xlarge
            - m5.2xlarge
            - c5.large
            - c5.xlarge
            - r5.large
            - r5.xlarge
          enumNames:
            - t3.nano (2 vCPU, 0.5 GB)
            - t3.micro (2 vCPU, 1 GB)
            - t3.small (2 vCPU, 2 GB)
            - t3.medium (2 vCPU, 4 GB)
            - t3.large (2 vCPU, 8 GB)
            - t3.xlarge (4 vCPU, 16 GB)
            - t3.2xlarge (8 vCPU, 32 GB)
            - m5.large (2 vCPU, 8 GB)
            - m5.xlarge (4 vCPU, 16 GB)
            - m5.2xlarge (8 vCPU, 32 GB)
            - c5.large (2 vCPU, 4 GB) - Compute
            - c5.xlarge (4 vCPU, 8 GB) - Compute
            - r5.large (2 vCPU, 16 GB) - Memory
            - r5.xlarge (4 vCPU, 32 GB) - Memory
        amiId:
          title: AMI ID (Optional)
          type: string
          description: Leave empty for latest Amazon Linux 2023
          default: ""
        vpcId:
          title: VPC ID
          type: string
          description: VPC where the instance will be created
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: Resource
              spec.type: vpc
        subnetId:
          title: Subnet ID
          type: string
          description: Subnet for the instance

    - title: Storage Configuration
      properties:
        rootVolumeSize:
          title: Root Volume Size (GB)
          type: number
          description: Size of the root EBS volume (minimum 30GB)
          default: 30
          minimum: 30
          maximum: 500
        rootVolumeType:
          title: Root Volume Type
          type: string
          description: EBS volume type
          default: gp3
          enum:
            - gp3
            - gp2
            - io1
            - io2
          enumNames:
            - GP3 (Recommended)
            - GP2 (Legacy)
            - IO1 (Provisioned IOPS)
            - IO2 (Provisioned IOPS)

    - title: Network Configuration
      properties:
        associatePublicIp:
          title: Associate Public IP
          type: boolean
          description: Assign a public IP address to the instance
          default: false
        additionalSecurityGroupIds:
          title: Additional Security Groups
          type: array
          description: Additional security group IDs to attach
          items:
            type: string
          default: []

    - title: IAM Configuration
      properties:
        additionalIamPolicies:
          title: Additional IAM Policies
          type: array
          description: Additional IAM policy ARNs to attach
          items:
            type: string
          default: []
          ui:help: |
            Common policies:
            - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
            - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess

    - title: Monitoring & Metadata
      required:
        - environment
      properties:
        environment:
          title: Environment
          type: string
          description: Deployment environment
          default: dev
          enum:
            - dev
            - staging
            - prod
        enableDetailedMonitoring:
          title: Enable Detailed Monitoring
          type: boolean
          description: Enable detailed CloudWatch monitoring (additional cost)
          default: false
        owner:
          title: Owner
          type: string
          description: Owner of this resource
          default: ${{ user.entity.metadata.name | default('unknown') }}
          ui:readonly: true
        ownerEmail:
          title: Owner Email
          type: string
          description: Email of the resource owner
          default: ${{ user.entity.spec.profile.email | default('unknown@example.com') }}
          ui:readonly: true

  steps:
    - id: fetch-template
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          name: ${{ parameters.name }}
          instanceType: ${{ parameters.instanceType }}
          amiId: ${{ parameters.amiId }}
          vpcId: ${{ parameters.vpcId }}
          subnetId: ${{ parameters.subnetId }}
          rootVolumeSize: ${{ parameters.rootVolumeSize }}
          rootVolumeType: ${{ parameters.rootVolumeType }}
          associatePublicIp: ${{ parameters.associatePublicIp }}
          additionalSecurityGroupIds: ${{ parameters.additionalSecurityGroupIds }}
          additionalIamPolicies: ${{ parameters.additionalIamPolicies }}
          environment: ${{ parameters.environment }}
          enableDetailedMonitoring: ${{ parameters.enableDetailedMonitoring }}
          owner: ${{ parameters.owner }}
          ownerEmail: ${{ parameters.ownerEmail }}

    - id: terraform-apply
      name: Apply Terraform
      action: terraform:apply
      input:
        terraformDir: ./output
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: ec2/${{ parameters.owner }}/${{ parameters.name }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        variables:
          instance_name: ${{ parameters.name }}
          instance_type: ${{ parameters.instanceType }}
          ami_id: ${{ parameters.amiId }}
          vpc_id: ${{ parameters.vpcId }}
          subnet_id: ${{ parameters.subnetId }}
          root_volume_size: "${{ parameters.rootVolumeSize }}"
          root_volume_type: ${{ parameters.rootVolumeType }}
          associate_public_ip: "${{ parameters.associatePublicIp }}"
          additional_security_group_ids: ${{ parameters.additionalSecurityGroupIds | dump }}
          additional_iam_policies: ${{ parameters.additionalIamPolicies | dump }}
          environment: ${{ parameters.environment }}
          enable_detailed_monitoring: "${{ parameters.enableDetailedMonitoring }}"
          owner: ${{ parameters.owner }}
          owner_email: ${{ parameters.ownerEmail }}
          project_name: ${{ parameters.name }}
        ownerEmail: ${{ parameters.ownerEmail }}
        resourceOwner: ${{ parameters.ownerEmail }}
        autoApprove: true

  output:
    links:
      - title: SSM Session Manager
        url: ${{ steps['terraform-apply'].output.outputs.ssm_console_url }}
        icon: terminal
      - title: EC2 Console
        url: "https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#InstanceDetails:instanceId=${{ steps['terraform-apply'].output.outputs.instance_id }}"
        icon: cloud
      - title: View in Catalog
        entityRef: resource:default/ec2-${{ parameters.name }}
    text:
      - title: SSM Connect Command
        content: ${{ steps['terraform-apply'].output.outputs.ssm_connect_command }}
      - title: Instance ID
        content: ${{ steps['terraform-apply'].output.outputs.instance_id }}
      - title: Private IP
        content: ${{ steps['terraform-apply'].output.outputs.private_ip }}
