apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdynamodbtable.darede.io
  labels:
    crossplane.io/xrd: xdynamodbtables.darede.io
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: darede.io/v1alpha1
    kind: XDynamoDBTable

  resources:
    # DynamoDB Table
    - name: dynamodb-table
      base:
        apiVersion: dynamodb.aws.upbound.io/v1beta1
        kind: Table
        spec:
          forProvider:
            region: us-east-1
            billingMode: PAY_PER_REQUEST
            pointInTimeRecoveryEnabled: true
            serverSideEncryption:
              - enabled: true
            tags:
              managed-by: crossplane
              created-via: backstage
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tableName
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.billingMode
          toFieldPath: spec.forProvider.billingMode
        - type: FromCompositeFieldPath
          fromFieldPath: spec.readCapacityUnits
          toFieldPath: spec.forProvider.readCapacity
        - type: FromCompositeFieldPath
          fromFieldPath: spec.writeCapacityUnits
          toFieldPath: spec.forProvider.writeCapacity
        - type: FromCompositeFieldPath
          fromFieldPath: spec.hashKey
          toFieldPath: spec.forProvider.attribute[0].name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.hashKeyType
          toFieldPath: spec.forProvider.attribute[0].type
        - type: FromCompositeFieldPath
          fromFieldPath: spec.hashKey
          toFieldPath: spec.forProvider.hashKey
        - type: FromCompositeFieldPath
          fromFieldPath: spec.rangeKey
          toFieldPath: spec.forProvider.rangeKey
        - type: FromCompositeFieldPath
          fromFieldPath: spec.rangeKey
          toFieldPath: spec.forProvider.attribute[1].name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.rangeKeyType
          toFieldPath: spec.forProvider.attribute[1].type
        - type: FromCompositeFieldPath
          fromFieldPath: spec.pointInTimeRecovery
          toFieldPath: spec.forProvider.pointInTimeRecovery[0].enabled
        - type: FromCompositeFieldPath
          fromFieldPath: spec.encryption
          toFieldPath: spec.forProvider.serverSideEncryption[0].enabled
        - type: FromCompositeFieldPath
          fromFieldPath: spec.streamEnabled
          toFieldPath: spec.forProvider.streamSpecification[0].streamEnabled
        - type: FromCompositeFieldPath
          fromFieldPath: spec.streamViewType
          toFieldPath: spec.forProvider.streamSpecification[0].streamViewType
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              keepMapValues: true
        # Copy status back
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.tableArn
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.tableId

    # TTL Configuration
    - name: dynamodb-ttl
      base:
        apiVersion: dynamodb.aws.upbound.io/v1beta1
        kind: TableItemAttribute
        spec:
          forProvider:
            region: us-east-1
            attributeName: ttl
            enabled: false
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tableName
          toFieldPath: spec.forProvider.tableName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.ttlAttributeName
          toFieldPath: spec.forProvider.attributeName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.timeToLive
          toFieldPath: spec.forProvider.enabled
