apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdynamodbtables.darede.io
spec:
  group: darede.io
  names:
    kind: XDynamoDBTable
    plural: xdynamodbtables
  claimNames:
    kind: DynamoDBTable
    plural: dynamodbtables

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tableName:
                  type: string
                  description: "Nome da tabela DynamoDB"
                region:
                  type: string
                  description: "Região AWS"
                  default: "us-east-1"
                  enum:
                    - us-east-1
                    - us-east-2
                    - us-west-1
                    - us-west-2
                billingMode:
                  type: string
                  description: "Modo de cobrança"
                  default: "PAY_PER_REQUEST"
                  enum:
                    - PAY_PER_REQUEST
                    - PROVISIONED
                readCapacityUnits:
                  type: integer
                  description: "Unidades de leitura (apenas para PROVISIONED)"
                  default: 5
                  minimum: 1
                  maximum: 40000
                writeCapacityUnits:
                  type: integer
                  description: "Unidades de escrita (apenas para PROVISIONED)"
                  default: 5
                  minimum: 1
                  maximum: 40000
                hashKey:
                  type: string
                  description: "Nome da chave de partição"
                  default: "id"
                hashKeyType:
                  type: string
                  description: "Tipo da chave de partição"
                  default: "S"
                  enum:
                    - "S"  # String
                    - "N"  # Number
                    - "B"  # Binary
                rangeKey:
                  type: string
                  description: "Nome da chave de ordenação (opcional)"
                rangeKeyType:
                  type: string
                  description: "Tipo da chave de ordenação"
                  enum:
                    - "S"
                    - "N"
                    - "B"
                pointInTimeRecovery:
                  type: boolean
                  description: "Habilitar Point-in-Time Recovery"
                  default: true
                encryption:
                  type: boolean
                  description: "Habilitar criptografia"
                  default: true
                streamEnabled:
                  type: boolean
                  description: "Habilitar DynamoDB Streams"
                  default: false
                streamViewType:
                  type: string
                  description: "Tipo de visualização do stream"
                  default: "NEW_AND_OLD_IMAGES"
                  enum:
                    - KEYS_ONLY
                    - NEW_IMAGE
                    - OLD_IMAGE
                    - NEW_AND_OLD_IMAGES
                timeToLive:
                  type: boolean
                  description: "Habilitar TTL"
                  default: false
                ttlAttributeName:
                  type: string
                  description: "Nome do atributo TTL"
                  default: "ttl"
                tags:
                  type: object
                  description: "Tags customizadas"
                  additionalProperties:
                    type: string
              required:
                - tableName
                - hashKey
            status:
              type: object
              properties:
                tableArn:
                  type: string
                  description: "ARN da tabela"
                tableId:
                  type: string
                  description: "ID da tabela"
                status:
                  type: string
                  description: "Status da tabela"
