apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksclusters.platform.darede.io
spec:
  group: platform.darede.io
  names:
    kind: XEKSCluster
    plural: xeksclusters
  claimNames:
    kind: EKSCluster
    plural: eksclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterName:
                  type: string
                  description: Nome do cluster EKS
                region:
                  type: string
                  description: Região AWS
                  default: us-east-1
                kubernetesVersion:
                  type: string
                  description: Versão do Kubernetes
                  default: "1.33"
                nodeGroupSize:
                  type: object
                  description: Tamanho do node group
                  properties:
                    min:
                      type: integer
                      default: 2
                    max:
                      type: integer
                      default: 10
                    desired:
                      type: integer
                      default: 3
                  required:
                    - min
                    - max
                    - desired
                nodeInstanceType:
                  type: string
                  description: Tipo de instância dos nodes
                  default: t3.medium
                  enum:
                    - t3.small
                    - t3.medium
                    - t3.large
                    - t3.xlarge
              required:
                - clusterName
                - region
            status:
              type: object
              properties:
                clusterStatus:
                  type: string
                clusterEndpoint:
                  type: string
                vpcId:
                  type: string
