apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xrdsinstance.darede.io
  labels:
    crossplane.io/xrd: xrdsinstances.darede.io
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: darede.io/v1alpha1
    kind: XRDSInstance

  resources:
    - name: db-subnet-group
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: SubnetGroup
        spec:
          forProvider:
            region: us-east-1
            description: "Subnet group for RDS instance"
            tags:
              managed-by: crossplane
              created-via: backstage
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.instanceName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-subnet-group"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.subnetIds
          toFieldPath: spec.forProvider.subnetIds

    - name: rds-instance
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            region: us-east-1
            engine: postgres
            engineVersion: "15.4"
            instanceClass: db.t3.micro
            allocatedStorage: 20
            storageType: gp3
            storageEncrypted: true
            username: admin
            passwordSecretRef:
              name: rds-password
              namespace: crossplane-system
              key: password
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            publiclyAccessible: false
            backupRetentionPeriod: 7
            skipFinalSnapshot: true
            tags:
              managed-by: crossplane
              created-via: backstage
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.instanceName
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.engine
          toFieldPath: spec.forProvider.engine
        - type: FromCompositeFieldPath
          fromFieldPath: spec.engineVersion
          toFieldPath: spec.forProvider.engineVersion
        - type: FromCompositeFieldPath
          fromFieldPath: spec.instanceClass
          toFieldPath: spec.forProvider.instanceClass
        - type: FromCompositeFieldPath
          fromFieldPath: spec.allocatedStorage
          toFieldPath: spec.forProvider.allocatedStorage
        - type: FromCompositeFieldPath
          fromFieldPath: spec.dbName
          toFieldPath: spec.forProvider.dbName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.masterUsername
          toFieldPath: spec.forProvider.username
        - type: FromCompositeFieldPath
          fromFieldPath: spec.masterPasswordSecretName
          toFieldPath: spec.forProvider.passwordSecretRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.securityGroupIds
          toFieldPath: spec.forProvider.vpcSecurityGroupIds
        - type: FromCompositeFieldPath
          fromFieldPath: spec.publiclyAccessible
          toFieldPath: spec.forProvider.publiclyAccessible
        - type: FromCompositeFieldPath
          fromFieldPath: spec.backupRetentionPeriod
          toFieldPath: spec.forProvider.backupRetentionPeriod
        - type: FromCompositeFieldPath
          fromFieldPath: spec.multiAz
          toFieldPath: spec.forProvider.multiAz
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              keepMapValues: true
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.instanceId
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.endpoint
          toFieldPath: status.endpoint
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.port
          toFieldPath: status.port
