apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrdsinstances.darede.io
spec:
  group: darede.io
  names:
    kind: XRDSInstance
    plural: xrdsinstances
  claimNames:
    kind: RDSInstance
    plural: rdsinstances

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instanceName:
                  type: string
                  description: "Nome da instância RDS"
                engine:
                  type: string
                  description: "Engine do banco de dados"
                  default: "postgres"
                  enum:
                    - postgres
                    - mysql
                    - mariadb
                engineVersion:
                  type: string
                  description: "Versão do engine"
                  default: "15.4"
                instanceClass:
                  type: string
                  description: "Classe da instância"
                  default: "db.t3.micro"
                  enum:
                    - db.t3.micro
                    - db.t3.small
                    - db.t3.medium
                    - db.t3.large
                allocatedStorage:
                  type: integer
                  description: "Tamanho do storage em GB"
                  default: 20
                  minimum: 20
                  maximum: 65536
                storageType:
                  type: string
                  description: "Tipo de storage"
                  default: "gp3"
                  enum:
                    - gp3
                    - gp2
                    - io1
                    - io2
                iops:
                  type: integer
                  description: "IOPS provisionado (io1, io2, gp3)"
                  default: 3000
                storageAutoscaling:
                  type: object
                  description: "Configuração de autoscaling do storage"
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    maxAllocatedStorage:
                      type: integer
                      description: "Limite máximo de storage em GB"
                      default: 100
                dbName:
                  type: string
                  description: "Nome do database inicial"
                masterUsername:
                  type: string
                  description: "Username do master user"
                  default: "admin"
                masterPasswordSecretName:
                  type: string
                  description: "Nome do secret K8s contendo a senha (key: password)"
                region:
                  type: string
                  description: "Região AWS"
                  default: "us-east-1"
                subnetIds:
                  type: array
                  description: "IDs das subnets para o subnet group"
                  items:
                    type: string
                securityGroupIds:
                  type: array
                  description: "IDs dos Security Groups"
                  items:
                    type: string
                publiclyAccessible:
                  type: boolean
                  description: "Se a instância será publicamente acessível"
                  default: false
                backupRetentionPeriod:
                  type: integer
                  description: "Período de retenção de backup em dias"
                  default: 7
                multiAz:
                  type: boolean
                  description: "Habilitar Multi-AZ"
                  default: false
                tags:
                  type: object
                  description: "Tags customizadas"
                  additionalProperties:
                    type: string
              required:
                - instanceName
                - dbName
                - masterPasswordSecretName
                - subnetIds
            status:
              type: object
              properties:
                instanceId:
                  type: string
                  description: "Identifier da instância RDS"
                endpoint:
                  type: string
                  description: "Endpoint de conexão"
                port:
                  type: integer
                  description: "Porta de conexão"
