apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rds-instance-m
  labels:
    crossplane.io/xrd: xrdsinstances.platform.darede.io
    provider: aws
    size: M
spec:
  compositeTypeRef:
    apiVersion: platform.darede.io/v1alpha1
    kind: XRDSInstance

  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.databaseName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-m"

  resources:
    - name: db-subnet-group
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: SubnetGroup
        spec:
          forProvider:
            description: "Subnet group for RDS instance (Size: M)"
            tags:
              managed-by: crossplane
              created-via: backstage
              size: M
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.databaseName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-m-subnet-group"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.subnetIds
          toFieldPath: spec.forProvider.subnetIds

    - name: rds-instance
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            # T-shirt size M: Medium/Staging
            instanceClass: db.t3.small
            allocatedStorage: 50
            storageType: gp3
            storageEncrypted: true
            engine: postgres
            engineVersion: "15.4"
            username: admin
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            publiclyAccessible: false
            backupRetentionPeriod: 7
            skipFinalSnapshot: true
            multiAz: false
            tags:
              managed-by: crossplane
              created-via: backstage
              size: M
          providerConfigRef:
            name: default
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.engine
          toFieldPath: spec.forProvider.engine
        - type: FromCompositeFieldPath
          fromFieldPath: spec.engineVersion
          toFieldPath: spec.forProvider.engineVersion
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.databaseName
          toFieldPath: spec.forProvider.dbName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.masterUsername
          toFieldPath: spec.forProvider.username
        - type: FromCompositeFieldPath
          fromFieldPath: spec.vpcSecurityGroupIds
          toFieldPath: spec.forProvider.vpcSecurityGroupIds
        - type: FromCompositeFieldPath
          fromFieldPath: spec.publiclyAccessible
          toFieldPath: spec.forProvider.publiclyAccessible
        - type: FromCompositeFieldPath
          fromFieldPath: spec.backupRetentionPeriod
          toFieldPath: spec.forProvider.backupRetentionPeriod
        - type: FromCompositeFieldPath
          fromFieldPath: spec.storageEncrypted
          toFieldPath: spec.forProvider.storageEncrypted
        - type: FromCompositeFieldPath
          fromFieldPath: spec.multiAZ
          toFieldPath: spec.forProvider.multiAz
        - type: FromCompositeFieldPath
          fromFieldPath: spec.writeConnectionSecretToRef.name
          toFieldPath: spec.writeConnectionSecretToRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tags
          toFieldPath: spec.forProvider.tags
          policy:
            fromFieldPath: Optional
            mergeOptions:
              appendSlice: false
              keepMapValues: true

        # Status patches
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.endpoint
          toFieldPath: status.endpoint
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.port
          toFieldPath: status.port
        - type: ToCompositeFieldPath
          fromFieldPath: spec.forProvider.instanceClass
          toFieldPath: status.instanceClass
        - type: ToCompositeFieldPath
          fromFieldPath: spec.forProvider.allocatedStorage
          toFieldPath: status.allocatedStorage
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.status
          toFieldPath: status.status
