apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3-bucket
  labels:
    crossplane.io/xrd: xs3buckets.platform.darede.io
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: platform.darede.io/v1alpha1
    kind: XS3Bucket

  resources:
    - name: s3-bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            tags:
              managed-by: crossplane
              created-via: backstage
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: spec.forProvider.bucket
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tags
          toFieldPath: spec.forProvider.tags
          policy:
            fromFieldPath: Optional
            mergeOptions:
              appendSlice: false
              keepMapValues: true

        # Status patches
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.bucketArn
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.bucketDomainName
          toFieldPath: status.bucketDomainName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.bucketRegionalDomainName
          toFieldPath: status.bucketRegionalDomainName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.region
          toFieldPath: status.region

    - name: bucket-public-access-block
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketPublicAccessBlock
        spec:
          forProvider:
            blockPublicAcls: true
            blockPublicPolicy: true
            ignorePublicAcls: true
            restrictPublicBuckets: true
            bucketSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-pab"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.publicAccessBlock
          toFieldPath: spec.forProvider.blockPublicAcls
        - type: FromCompositeFieldPath
          fromFieldPath: spec.publicAccessBlock
          toFieldPath: spec.forProvider.blockPublicPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.publicAccessBlock
          toFieldPath: spec.forProvider.ignorePublicAcls
        - type: FromCompositeFieldPath
          fromFieldPath: spec.publicAccessBlock
          toFieldPath: spec.forProvider.restrictPublicBuckets

    - name: bucket-versioning
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketVersioning
        spec:
          forProvider:
            bucketSelector:
              matchControllerRef: true
            versioningConfiguration:
              - status: Suspended
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-versioning"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.versioning
          toFieldPath: spec.forProvider.versioningConfiguration[0].status
          transforms:
            - type: map
              map:
                "true": "Enabled"
                "false": "Suspended"

    - name: bucket-server-side-encryption
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketServerSideEncryptionConfiguration
        spec:
          forProvider:
            bucketSelector:
              matchControllerRef: true
            rule:
              - applyServerSideEncryptionByDefault:
                  - sseAlgorithm: AES256
                bucketKeyEnabled: true
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-sse"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.encryption.enabled
          toFieldPath: spec.forProvider.rule[0].applyServerSideEncryptionByDefault[0].sseAlgorithm
          transforms:
            - type: map
              map:
                "true": "AES256"
                "false": "AES256"
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.encryption.sseAlgorithm
          toFieldPath: spec.forProvider.rule[0].applyServerSideEncryptionByDefault[0].sseAlgorithm
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.encryption.kmsMasterKeyId
          toFieldPath: spec.forProvider.rule[0].applyServerSideEncryptionByDefault[0].kmsMasterKeyId
          policy:
            fromFieldPath: Optional
