apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xs3buckets.darede.io
spec:
  group: darede.io
  names:
    kind: XS3Bucket
    plural: xs3buckets
  claimNames:
    kind: S3Bucket
    plural: s3buckets

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bucketName:
                  type: string
                  description: "Nome único do bucket S3"
                region:
                  type: string
                  description: "Região AWS onde criar o bucket"
                  default: "us-east-1"
                enableVersioning:
                  type: boolean
                  description: "Habilitar versionamento de objetos"
                  default: true
                tags:
                  type: object
                  description: "Tags customizadas para o bucket"
                  additionalProperties:
                    type: string
              required:
                - bucketName
            status:
              type: object
              properties:
                bucketArn:
                  type: string
                  description: "ARN do bucket criado"
                bucketId:
                  type: string
                  description: "ID do bucket criado"
