apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsecrets.darede.io
spec:
  group: darede.io
  names:
    kind: XSecret
    plural: xsecrets
  claimNames:
    kind: Secret
    plural: secrets

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretName:
                  type: string
                  description: "Nome do secret no AWS Secrets Manager"
                region:
                  type: string
                  description: "Região AWS"
                  default: "us-east-1"
                  enum:
                    - us-east-1
                    - us-east-2
                    - us-west-1
                    - us-west-2
                description:
                  type: string
                  description: "Descrição do secret"
                secretType:
                  type: string
                  description: "Tipo do secret"
                  default: "plaintext"
                  enum:
                    - plaintext
                    - json
                    - binary
                secretValue:
                  type: string
                  description: "Valor inicial do secret (será criado vazio se não fornecido)"
                  default: "{}"
                kmsKeyId:
                  type: string
                  description: "KMS Key ID para criptografia (opcional)"
                automaticRotation:
                  type: boolean
                  description: "Habilitar rotação automática"
                  default: false
                rotationDays:
                  type: integer
                  description: "Dias para rotação automática"
                  default: 30
                  minimum: 1
                  maximum: 365
                recoveryWindowInDays:
                  type: integer
                  description: "Janela de recuperação em dias"
                  default: 7
                  minimum: 7
                  maximum: 30
                tags:
                  type: object
                  description: "Tags customizadas"
                  additionalProperties:
                    type: string
              required:
                - secretName
            status:
              type: object
              properties:
                secretArn:
                  type: string
                  description: "ARN do secret"
                secretId:
                  type: string
                  description: "ID do secret"
                versionId:
                  type: string
                  description: "Version ID atual"
