apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsecuritygroup.darede.io
  labels:
    crossplane.io/xrd: xsecuritygroups.darede.io
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: darede.io/v1alpha1
    kind: XSecurityGroup

  resources:
    - name: security-group
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            region: us-east-1
            description: "Security Group managed by Crossplane"
            tags:
              managed-by: crossplane
              created-via: backstage
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.groupName
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.groupName
          toFieldPath: spec.forProvider.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.description
          toFieldPath: spec.forProvider.description
        - type: FromCompositeFieldPath
          fromFieldPath: spec.vpcId
          toFieldPath: spec.forProvider.vpcId
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              keepMapValues: true
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.securityGroupId

    - name: ingress-ssh
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            region: us-east-1
            type: ingress
            protocol: tcp
            fromPort: 22
            toPort: 22
            cidrBlocks:
              - 0.0.0.0/0
            securityGroupIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.groupName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-ingress-ssh"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

    - name: ingress-http
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            region: us-east-1
            type: ingress
            protocol: tcp
            fromPort: 80
            toPort: 80
            cidrBlocks:
              - 0.0.0.0/0
            securityGroupIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.groupName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-ingress-http"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

    - name: ingress-https
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            region: us-east-1
            type: ingress
            protocol: tcp
            fromPort: 443
            toPort: 443
            cidrBlocks:
              - 0.0.0.0/0
            securityGroupIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.groupName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-ingress-https"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

    - name: egress-all
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            region: us-east-1
            type: egress
            protocol: "-1"
            fromPort: 0
            toPort: 0
            cidrBlocks:
              - 0.0.0.0/0
            securityGroupIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.groupName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-egress-all"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
