apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsecuritygroups.darede.io
spec:
  group: darede.io
  names:
    kind: XSecurityGroup
    plural: xsecuritygroups
  claimNames:
    kind: SecurityGroup
    plural: securitygroups

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                groupName:
                  type: string
                  description: "Nome do Security Group"
                description:
                  type: string
                  description: "Descrição do Security Group"
                  default: "Security Group criado via Backstage"
                vpcId:
                  type: string
                  description: "ID da VPC (opcional se usar vpcName)"
                vpcName:
                  type: string
                  description: "Nome da VPC (referência ao composite)"
                region:
                  type: string
                  description: "Região AWS"
                  default: "us-east-1"
                ingressRules:
                  type: array
                  description: "Regras de ingress"
                  items:
                    type: object
                    properties:
                      protocol:
                        type: string
                        default: "tcp"
                      fromPort:
                        type: integer
                      toPort:
                        type: integer
                      cidrBlocks:
                        type: array
                        items:
                          type: string
                      description:
                        type: string
                egressRules:
                  type: array
                  description: "Regras de egress"
                  items:
                    type: object
                    properties:
                      protocol:
                        type: string
                        default: "-1"
                      fromPort:
                        type: integer
                        default: 0
                      toPort:
                        type: integer
                        default: 0
                      cidrBlocks:
                        type: array
                        items:
                          type: string
                tags:
                  type: object
                  additionalProperties:
                    type: string
              required:
                - groupName
            status:
              type: object
              properties:
                securityGroupId:
                  type: string
