apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvpcs.darede.io
spec:
  group: darede.io
  names:
    kind: XVPC
    plural: xvpcs
  claimNames:
    kind: VPC
    plural: vpcs

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vpcName:
                  type: string
                  description: "Nome da VPC"
                cidrBlock:
                  type: string
                  description: "CIDR block da VPC"
                  default: "10.0.0.0/16"
                region:
                  type: string
                  description: "Região AWS"
                  default: "us-east-1"
                tags:
                  type: object
                  description: "Tags customizadas"
                  additionalProperties:
                    type: string
              required:
                - vpcName
            status:
              type: object
              properties:
                vpcId:
                  type: string
                  description: "ID da VPC criada"
