apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: user-management
  title: "👥 Manage Users & Groups"
  description: |
    Add users to admin or user groups. Only admins can execute this template.
  tags:
    - admin
    - users
    - rbac
    - management
spec:
  owner: platform-team
  type: admin

  parameters:
    - title: "User Information"
      required:
        - username
        - email
        - displayName
        - group
      properties:
        username:
          title: "Username"
          type: string
          description: "Backstage username (lowercase, no spaces)"
          pattern: '^[a-z][a-z0-9-]*$'
          ui:autofocus: true
        email:
          title: "Email"
          type: string
          format: email
          description: "User email address"
        displayName:
          title: "Display Name"
          type: string
          description: "Full name of the user"
        group:
          title: "Group"
          type: string
          description: "User group membership"
          enum:
            - admins
            - users
          enumNames:
            - "Administrators (full access)"
            - "Users (standard access)"
          default: users

  steps:
    - id: fetch-template
      name: Create User Catalog Entry
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./user-catalog
        values:
          username: ${{ parameters.username }}
          email: ${{ parameters.email }}
          displayName: ${{ parameters.displayName }}
          group: ${{ parameters.group }}

    - id: publish
      name: Publish to Catalog
      action: catalog:write
      input:
        filePath: ./user-catalog/user-${{ parameters.username }}.yaml
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: User
          metadata:
            name: ${{ parameters.username }}
            description: User managed via Backstage
          spec:
            profile:
              displayName: ${{ parameters.displayName }}
              email: ${{ parameters.email }}
            memberOf:
              - ${{ parameters.group }}

  output:
    text:
      - title: User Created
        content: |
          ✅ User **${{ parameters.displayName }}** (${{ parameters.username }}) created successfully!

          - Email: ${{ parameters.email }}
          - Group: ${{ parameters.group }}

          The user can now log in with their email via Cognito.
      - title: Next Steps
        content: |
          1. User must complete first login via Cognito
          2. Permissions will be applied based on group membership
    links:
      - title: "View User in Catalog"
        entityRef: user:default/${{ parameters.username }}
      - title: "Cognito Users"
        url: "https://console.aws.amazon.com/cognito"
