apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: user-management
  title: "👥 Manage Users & Groups"
  description: |
    Add users to admin or user groups. Only admins can execute this template.
  tags:
    - admin
    - users
    - rbac
    - management
spec:
  owner: platform-team
  type: admin

  parameters:
    - title: "User Information"
      required:
        - username
        - email
        - displayName
        - group
        - temporaryPassword
      properties:
        username:
          title: "Username"
          type: string
          description: "Backstage username (lowercase, no spaces)"
          pattern: '^[a-z][a-z0-9-]*$'
          ui:autofocus: true
        email:
          title: "Email"
          type: string
          format: email
          description: "User email address (will be used for Cognito login)"
        displayName:
          title: "Display Name"
          type: string
          description: "Full name of the user"
        temporaryPassword:
          title: "Temporary Password"
          type: string
          description: "Temporary password (min 8 chars, uppercase, lowercase, number, special char). User will be forced to change on first login."
          ui:widget: password
          ui:help: "Minimum 8 characters with uppercase, lowercase, number and special character"
        group:
          title: "Group"
          type: string
          description: "User group membership"
          enum:
            - admins
            - users
          enumNames:
            - "Administrators (full access)"
            - "Users (standard access)"
          default: users

  steps:
    - id: fetch-template
      name: Create User Catalog Entry
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./user-catalog
        values:
          username: ${{ parameters.username }}
          email: ${{ parameters.email }}
          displayName: ${{ parameters.displayName }}
          group: ${{ parameters.group }}

    - id: publish
      name: Publish to Catalog
      action: catalog:write
      input:
        filePath: ./user-catalog/user-${{ parameters.username }}.yaml
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: User
          metadata:
            name: ${{ parameters.username }}
            description: User managed via Backstage
          spec:
            profile:
              displayName: ${{ parameters.displayName }}
              email: ${{ parameters.email }}
            memberOf:
              - ${{ parameters.group }}

  output:
    text:
      - title: User Created
        content: |
          ✅ User **${{ parameters.displayName }}** (${{ parameters.username }}) created successfully!

          **Credentials:**
          - Email: ${{ parameters.email }}
          - Temporary Password: *(provided during creation)*
          - Group: ${{ parameters.group }}

          **⚠️ IMPORTANT:** The user must create this account in AWS Cognito manually or via AWS CLI with the temporary password provided.
      - title: Next Steps
        content: |
          **1. Create user in Cognito (Manual):**
          ```bash
          aws cognito-idp admin-create-user \
            --user-pool-id ${COGNITO_USER_POOL_ID} \
            --username ${{ parameters.email }} \
            --user-attributes Name=email,Value=${{ parameters.email }} Name=email_verified,Value=true \
            --temporary-password "<your-temp-password>" \
            --message-action SUPPRESS \
            --profile darede
          ```

          **2. User first login:**
          - Access: https://backstage.timedevops.click
          - Login with email: ${{ parameters.email }}
          - Use temporary password (will be forced to change)

          **3. Permissions:**
          - Backstage catalog updated with user and group
          - RBAC applied based on group membership
    links:
      - title: "View User in Catalog"
        entityRef: user:default/${{ parameters.username }}
      - title: "Cognito Users"
        url: "https://console.aws.amazon.com/cognito"
