apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: eks-${{ values.name }}
  description: "EKS Cluster: ${{ values.name }} (k8s ${{ values.kubernetesVersion }})"
  annotations:
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.infraRepo }}
    backstage.io/source-location: url:https://github.com/${{ values.githubOrg }}/${{ values.infraRepo }}/tree/main/platform/terraform/stacks/eks/${{ values.name }}
  links:
    - url: https://github.com/${{ values.githubOrg }}/${{ values.infraRepo }}/pulls?q=is%3Apr+eks-${{ values.name }}
      title: "🔄 Pull Requests"
      icon: github
    - url: https://console.aws.amazon.com/eks/home#/clusters/${{ values.name }}
      title: "☁️ AWS Console"
      icon: cloud
  tags: [aws, eks, kubernetes, terraform, "${{ values.environment }}"]
spec:
  type: eks-cluster
  lifecycle: ${{ values.environment }}
  owner: ${{ values.owner }}
  system: aws-infrastructure
