apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-dynamodb
  title: DynamoDB Table
  description: Create a DynamoDB table using Terraform (direct execution with RBAC)
  tags:
    - aws
    - dynamodb
    - terraform
    - database
    - nosql
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Table Configuration
      required:
        - name
        - environment
        - partitionKey
      properties:
        name:
          title: Table Name
          type: string
          pattern: '^[a-zA-Z0-9][a-zA-Z0-9_.-]*[a-zA-Z0-9]$'
          description: "Nome da tabela DynamoDB"
        environment:
          title: Environment
          type: string
          enum: [poc, dev, staging, prod]
          default: poc
        partitionKey:
          title: Partition Key (Hash Key)
          type: object
          required: [name, type]
          properties:
            name:
              title: Attribute Name
              type: string
              default: id
            type:
              title: Attribute Type
              type: string
              enum: [S, N, B]
              enumNames: ["String (S)", "Number (N)", "Binary (B)"]
              default: S
        sortKey:
          title: Sort Key (Range Key) - Optional
          type: object
          properties:
            name:
              title: Attribute Name
              type: string
            type:
              title: Attribute Type
              type: string
              enum: [S, N, B]
              enumNames: ["String (S)", "Number (N)", "Binary (B)"]

    - title: Capacity Configuration
      properties:
        billingMode:
          title: Billing Mode
          type: string
          enum: [PAY_PER_REQUEST, PROVISIONED]
          enumNames: ["On-Demand (PAY_PER_REQUEST)", "Provisioned Capacity"]
          default: PAY_PER_REQUEST
        readCapacity:
          title: Read Capacity Units (only for Provisioned)
          type: integer
          default: 5
          minimum: 1
          maximum: 10000
        writeCapacity:
          title: Write Capacity Units (only for Provisioned)
          type: integer
          default: 5
          minimum: 1
          maximum: 10000

    - title: Additional Features
      properties:
        enableTTL:
          title: Enable TTL (Time to Live)
          type: boolean
          default: false
        ttlAttribute:
          title: TTL Attribute Name
          type: string
          default: ttl
          description: "Attribute name for TTL (epoch timestamp)"
        enablePointInTimeRecovery:
          title: Enable Point-in-Time Recovery
          type: boolean
          default: true
        enableEncryption:
          title: Enable Server-Side Encryption
          type: boolean
          default: true
        streamEnabled:
          title: Enable DynamoDB Streams
          type: boolean
          default: false
        streamViewType:
          title: Stream View Type
          type: string
          enum: [KEYS_ONLY, NEW_IMAGE, OLD_IMAGE, NEW_AND_OLD_IMAGES]
          default: NEW_AND_OLD_IMAGES

    - title: Global Secondary Indexes (Optional)
      properties:
        globalSecondaryIndexes:
          title: Global Secondary Indexes
          type: array
          items:
            type: object
            required: [name, partitionKey]
            properties:
              name:
                title: Index Name
                type: string
              partitionKey:
                title: Partition Key
                type: string
              partitionKeyType:
                title: Partition Key Type
                type: string
                enum: [S, N, B]
                default: S
              sortKey:
                title: Sort Key (optional)
                type: string
              sortKeyType:
                title: Sort Key Type
                type: string
                enum: [S, N, B]
                default: S
              projectionType:
                title: Projection Type
                type: string
                enum: [ALL, KEYS_ONLY, INCLUDE]
                default: ALL
          ui:options:
            addable: true
            removable: true

    - title: Tags
      properties:
        tags:
          title: Custom Tags
          type: array
          items:
            type: object
            required: [key, value]
            properties:
              key:
                title: Key
                type: string
              value:
                title: Value
                type: string
          ui:options:
            addable: true
            removable: true

  steps:
    - id: fetch
      name: Generate Terraform Configuration
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./terraform
        values:
          name: ${{ parameters.name }}
          environment: ${{ parameters.environment }}
          partitionKey: ${{ parameters.partitionKey }}
          sortKey: ${{ parameters.sortKey }}
          billingMode: ${{ parameters.billingMode }}
          readCapacity: ${{ parameters.readCapacity }}
          writeCapacity: ${{ parameters.writeCapacity }}
          enableTTL: ${{ parameters.enableTTL }}
          ttlAttribute: ${{ parameters.ttlAttribute }}
          enablePointInTimeRecovery: ${{ parameters.enablePointInTimeRecovery }}
          enableEncryption: ${{ parameters.enableEncryption }}
          streamEnabled: ${{ parameters.streamEnabled }}
          streamViewType: ${{ parameters.streamViewType }}
          globalSecondaryIndexes: ${{ parameters.globalSecondaryIndexes }}
          owner: ${{ user.entity.metadata.name | default('unknown') }}
          ownerEmail: ${{ user.entity.spec.profile.email | default('unknown@example.com') }}
          tags: ${{ parameters.tags }}
          tfBackendBucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          tfBackendRegion: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}

    - id: terraform-apply
      name: Apply Terraform
      action: terraform:apply
      input:
        terraformDir: ./terraform
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: dynamodb/${{ user.entity.metadata.name | default('unknown') }}/${{ parameters.name }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        autoApprove: true

  output:
    links:
      - title: View DynamoDB in AWS Console
        url: https://console.aws.amazon.com/dynamodbv2/home?region=us-east-1#table?name=${{ parameters.name }}
      - title: View in Catalog
        entityRef: resource:default/dynamodb-${{ parameters.name }}
