#!/usr/bin/env bash
################################################################################
# Commit Rendered Manifests to Git
# Makes ArgoCD work by ensuring manifests exist in the Git repository
################################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

source "${SCRIPT_DIR}/utils.sh"

info "=========================================="
info "Committing Rendered Manifests to Git"
info "=========================================="

# Check if GITHUB_TOKEN is set
if [ -z "${GITHUB_TOKEN:-}" ]; then
    warn "GITHUB_TOKEN not set - commit will use current Git credentials"
    warn "For automated workflows, set GITHUB_TOKEN for authentication"
fi

cd "$REPO_ROOT"

# Check if there are changes to commit
if git diff --quiet && git diff --cached --quiet; then
    info "✓ No changes to commit"
    exit 0
fi

# Show what will be committed
info "Files to be committed:"
git status --short

# Add rendered files
info "Adding rendered manifests..."
git add platform/ argocd-apps/ packages/ 2>/dev/null || true

# Check if there are staged changes
if git diff --cached --quiet; then
    info "✓ No staged changes"
    exit 0
fi

# Commit with descriptive message
COMMIT_MSG="chore: render manifests for installation

Auto-generated by install script.
Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
"

info "Creating commit..."
git commit -m "$COMMIT_MSG" --no-verify

# Push to remote
info "Pushing to remote..."
if [ -n "${GITHUB_TOKEN:-}" ]; then
    # Use GITHUB_TOKEN for authentication
    REPO_URL=$(git remote get-url origin)
    # Convert SSH to HTTPS if needed
    if [[ "$REPO_URL" == git@github.com:* ]]; then
        REPO_URL=$(echo "$REPO_URL" | sed 's|git@github.com:|https://github.com/|' | sed 's|\.git$||')
    fi
    
    # Add token to URL
    REPO_URL_WITH_TOKEN=$(echo "$REPO_URL" | sed "s|https://|https://${GITHUB_TOKEN}@|")
    
    git push "$REPO_URL_WITH_TOKEN" HEAD 2>&1 | grep -v "$GITHUB_TOKEN" || true
else
    # Use existing Git credentials
    git push
fi

info "✓ Manifests committed and pushed"
info ""
info "ArgoCD should now be able to sync applications from Git"
