apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrdsinstances.platform.darede.io
spec:
  group: platform.darede.io
  names:
    kind: XRDSInstance
    plural: xrdsinstances
  claimNames:
    kind: RDSInstanceClaim
    plural: rdsinstanceclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: string
                enum: ["P", "M", "G"]
                description: |
                  T-shirt size for RDS instance:
                  - P (Pequeno): db.t3.micro, 20GB storage
                  - M (Médio): db.t3.small, 50GB storage
                  - G (Grande): db.t3.medium, 100GB storage
              engine:
                type: string
                enum: ["postgres", "mysql"]
                default: "postgres"
                description: Database engine type
              engineVersion:
                type: string
                description: Database engine version (e.g., "15.4" for PostgreSQL, "8.0.35" for MySQL)
              databaseName:
                type: string
                description: Name of the initial database to create
                pattern: '^[a-zA-Z][a-zA-Z0-9_]*$'
              masterUsername:
                type: string
                default: "admin"
                description: Master username for database access
              subnetIds:
                type: array
                items:
                  type: string
                description: List of subnet IDs for DB subnet group (must be in different AZs)
                minItems: 2
              vpcSecurityGroupIds:
                type: array
                items:
                  type: string
                description: List of VPC security group IDs to allow database access
                minItems: 1
              publiclyAccessible:
                type: boolean
                default: false
                description: Whether the database should be publicly accessible (NOT recommended for production)
              backupRetentionPeriod:
                type: integer
                default: 7
                description: Number of days to retain automated backups (0-35)
                minimum: 0
                maximum: 35
              multiAZ:
                type: boolean
                default: false
                description: Enable Multi-AZ deployment for high availability
              storageEncrypted:
                type: boolean
                default: true
                description: Enable storage encryption at rest
              writeConnectionSecretToRef:
                type: object
                description: Reference to secret where database credentials will be stored
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
              tags:
                type: object
                additionalProperties:
                  type: string
                description: Additional AWS tags for the RDS instance
            required:
            - size
            - databaseName
            - subnetIds
            - vpcSecurityGroupIds
            - writeConnectionSecretToRef
          status:
            type: object
            properties:
              endpoint:
                type: string
                description: Database endpoint hostname
              port:
                type: integer
                description: Database port number
              instanceClass:
                type: string
                description: Actual instance class provisioned based on size
              allocatedStorage:
                type: integer
                description: Actual storage size in GB based on size
              status:
                type: string
                description: Current status of the RDS instance
