apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xs3buckets.platform.darede.io
spec:
  group: platform.darede.io
  names:
    kind: XS3Bucket
    plural: xs3buckets
  claimNames:
    kind: S3BucketClaim
    plural: s3bucketclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              bucketName:
                type: string
                description: Name of the S3 bucket (must be globally unique across all AWS accounts)
                pattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
              publicAccessBlock:
                type: boolean
                default: true
                description: Block all public access to the bucket (recommended for security)
              versioning:
                type: boolean
                default: false
                description: Enable versioning to keep multiple variants of an object
              encryption:
                type: object
                description: Server-side encryption configuration
                properties:
                  enabled:
                    type: boolean
                    default: true
                  sseAlgorithm:
                    type: string
                    enum: ["AES256", "aws:kms"]
                    default: "AES256"
                  kmsMasterKeyId:
                    type: string
                    description: KMS key ID for encryption (only if sseAlgorithm is aws:kms)
              lifecycleRules:
                type: array
                description: Lifecycle rules for automatic object expiration/transition
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    enabled:
                      type: boolean
                    prefix:
                      type: string
                    expirationDays:
                      type: integer
                    transitionDays:
                      type: integer
                    storageClass:
                      type: string
                      enum: ["GLACIER", "DEEP_ARCHIVE", "INTELLIGENT_TIERING"]
              corsRules:
                type: array
                description: CORS rules for cross-origin resource sharing
                items:
                  type: object
                  properties:
                    allowedOrigins:
                      type: array
                      items:
                        type: string
                    allowedMethods:
                      type: array
                      items:
                        type: string
                        enum: ["GET", "PUT", "POST", "DELETE", "HEAD"]
                    allowedHeaders:
                      type: array
                      items:
                        type: string
                    maxAgeSeconds:
                      type: integer
              tags:
                type: object
                additionalProperties:
                  type: string
                description: Additional AWS tags for the bucket
            required:
            - bucketName
          status:
            type: object
            properties:
              bucketArn:
                type: string
                description: ARN of the S3 bucket
              bucketDomainName:
                type: string
                description: Domain name of the S3 bucket
              bucketRegionalDomainName:
                type: string
                description: Regional domain name of the S3 bucket
              region:
                type: string
                description: AWS region where the bucket is created
