apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      name: loki-canary
      jsonPointers:
        - /spec
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.41.4
    helm:
      valuesObject:
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
            path_prefix: /var/loki
          storage:
            type: s3
            bucketNames:
              chunks: idp-poc-darede-cluster-loki-chunks-95ad02
            s3:
              region: us-east-1
              insecure: false
          schemaConfig:
            configs:
              - from: 2024-01-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
        singleBinary:
          replicas: 1
          persistence:
            enabled: false
          extraVolumes:
            - name: loki-tmp-storage
              emptyDir: {}
          extraVolumeMounts:
            - name: loki-tmp-storage
              mountPath: /var/loki
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        serviceAccount:
          create: true
          name: loki
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::948881762705:role/idp-poc-darede-cluster-loki
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
        test:
          enabled: false
        lokiCanary:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: false # Disabled to prevent loki-canary recreation
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
