apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.3
    helm:
      valuesObject:
        config:
          clients:
            - url: http://loki-gateway.observability.svc.cluster.local:80/loki/api/v1/push
          snippets:
            pipelineStages:
              - cri: {}
              - json:
                  expressions:
                    level: level
                    msg: msg
                    timestamp: time
              - labels:
                  level:
              - timestamp:
                  source: timestamp
                  format: RFC3339Nano
        daemonset:
          enabled: true
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        # Avoid bootstrap nodes (they have limited capacity) using podAntiAffinity
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: role
                      operator: NotIn
                      values:
                        - karpenter-bootstrap
        tolerations:
          - effect: NoSchedule
            operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
