apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-s3-bucket
  title: S3 Bucket
  description: Create an S3 bucket using Terraform (direct execution)
  tags:
    - aws
    - s3
    - terraform
    - storage
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Bucket Configuration
      required:
        - name
        - environment
      properties:
        name:
          title: Bucket Name
          type: string
          pattern: '^[a-z0-9][a-z0-9.-]*[a-z0-9]$'
        environment:
          title: Environment
          type: string
          enum: [poc, dev, staging, prod]
          default: poc
        enableVersioning:
          title: Enable Versioning
          type: boolean
          default: true
        forceDestroy:
          title: Force Destroy (allow deletion with objects)
          type: boolean
          default: true

    - title: Tags
      properties:
        tags:
          title: Custom Tags
          type: array
          description: Add custom tags (key=value format)
          items:
            type: object
            required: [key, value]
            properties:
              key:
                title: Key
                type: string
              value:
                title: Value
                type: string
          ui:options:
            addable: true
            removable: true

  steps:
    - id: fetch
      name: Generate Terraform Configuration
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./terraform
        values:
          name: ${{ parameters.name }}
          environment: ${{ parameters.environment }}
          enableVersioning: ${{ parameters.enableVersioning }}
          forceDestroy: ${{ parameters.forceDestroy }}
          owner: ${{ user.entity.metadata.name | default('unknown') }}
          ownerEmail: ${{ user.entity.spec.profile.email | default('unknown@example.com') }}
          tags: ${{ parameters.tags }}
          tfBackendBucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          tfBackendRegion: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}

    - id: terraform-apply
      name: Apply Terraform
      action: terraform:apply
      input:
        terraformDir: ./terraform
        backendConfig:
          bucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          key: s3/${{ user.entity.metadata.name | default('unknown') }}/${{ parameters.name }}/terraform.tfstate
          region: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}
        autoApprove: true

    - id: catalog-register
      name: Register in Catalog
      action: catalog:register
      input:
        optional: true
        catalogInfoUrl: https://backstage.timedevops.click/catalog/default/resource/s3-${{ parameters.name }}

  output:
    links:
      - title: View S3 Bucket in AWS Console
        url: https://s3.console.aws.amazon.com/s3/buckets/${{ parameters.name }}
      - title: View in Catalog
        entityRef: resource:default/s3-${{ parameters.name }}
