apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-s3-bucket
  title: S3 Bucket
  description: Create an S3 bucket using Terraform and Atlantis (GitOps)
  tags:
    - aws
    - s3
    - terraform
    - storage
spec:
  owner: platform-team
  type: infrastructure
  parameters:
    - title: Bucket Configuration
      required:
        - name
        - environment
      properties:
        name:
          title: Bucket Name
          type: string
          pattern: '^[a-z0-9][a-z0-9.-]*[a-z0-9]$'
        environment:
          title: Environment
          type: string
          enum: [poc, dev, staging, prod]
          default: poc
        enableVersioning:
          title: Enable Versioning
          type: boolean
          default: true
        forceDestroy:
          title: Force Destroy (allow deletion with objects)
          type: boolean
          default: false

    - title: Tags
      properties:
        tags:
          title: Custom Tags
          type: array
          description: Add custom tags (key=value format)
          items:
            type: object
            required: [key, value]
            properties:
              key:
                title: Key
                type: string
              value:
                title: Value
                type: string
          ui:options:
            addable: true
            removable: true

  steps:
    - id: fetch
      name: Generate Terraform Configuration
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          name: ${{ parameters.name }}
          environment: ${{ parameters.environment }}
          enableVersioning: ${{ parameters.enableVersioning }}
          forceDestroy: ${{ parameters.forceDestroy }}
          # Auto-populate owner from Keycloak user identity
          owner: ${{ user.entity.metadata.name | default(user.entity.spec.profile.displayName) | default('unknown') }}
          ownerEmail: ${{ user.entity.spec.profile.email | default('') }}
          tags: ${{ parameters.tags }}
          # Platform config from environment variables
          githubOrg: ${{ env.GITHUB_ORG | default('darede-labs') }}
          infraRepo: ${{ env.INFRA_REPO | default('infrastructureidp') }}
          tfBackendBucket: ${{ env.TERRAFORM_BACKEND_BUCKET | default('poc-idp-tfstate') }}
          tfBackendRegion: ${{ env.TERRAFORM_BACKEND_REGION | default('us-east-1') }}

    - id: publish
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${{ env.GITHUB_ORG | default('darede-labs') }}&repo=${{ env.INFRA_REPO | default('infrastructureidp') }}
        branchName: infra/s3-${{ user.entity.metadata.name | default('user') }}-${{ parameters.name }}
        title: 'feat(s3): Create bucket ${{ parameters.name }} for ${{ user.entity.metadata.name | default("user") }}'
        description: |
          ## 🪣 New S3 Bucket Request

          | Property | Value |
          |----------|-------|
          | **Name** | `${{ parameters.name }}` |
          | **Owner** | `${{ user.entity.metadata.name | default("unknown") }}` |
          | **Environment** | `${{ parameters.environment }}` |
          | **Versioning** | `${{ parameters.enableVersioning }}` |

          ### GitOps Flow
          1. Atlantis runs `terraform plan` automatically
          2. Review the plan below
          3. Approve PR and comment `/atlantis apply`

          ### Owner Enforcement
          Only `${{ user.entity.metadata.name | default("unknown") }}` can delete this resource.

          ---
          *Created via Backstage by ${{ user.entity.metadata.name | default("unknown") }}*
        sourcePath: ./output
        # User-segregated path: s3/{username}/{resource_name}
        targetPath: platform/terraform/stacks/s3/${{ user.entity.metadata.name | default('shared') }}/${{ parameters.name }}

  output:
    links:
      - title: Pull Request
        url: ${{ steps['publish'].output.remoteUrl }}
